-- DEPRECATED. Do not run this file.
--
-- It previously created paidly as PRIVATE and only uid/org-path RLS.
-- Pasting it overwrites production policies (logo-% writes, public read)
-- and makes /object/public/paidly/* return HTTP 400 "Bucket not found".
--
-- Use supabase/schema.postgres.sql (or supabase db push).
-- Canonical model: docs/SUPABASE_STORAGE.md
--
-- Desired state:
--   paidly = PUBLIC
--   paths: logo-{uuid}.{ext}, document-logos/{userId}/..., inventory/{userId}/...
--   receipts, bank-details, activities, profile-logos = PRIVATE
