-- DEPRECATED. Do not run this file.
--
-- It dropped org/admin storage policies and recreated uid-first-segment
-- rules on paidly only. That removes "Public can read paidly assets" and
-- "Users can upload paidly assets" (logo-% / document-logos/%).
--
-- Use supabase/schema.postgres.sql or supabase db push.
-- Canonical model: docs/SUPABASE_STORAGE.md
