#!/bin/bash

# View Invoice Action - Quick Test Script
# This script helps you manually test the View Invoice functionality

echo "================================================"
echo "  VIEW INVOICE ACTION - MANUAL TEST GUIDE"
echo "================================================"
echo ""
echo "✅ Server Status: Running at http://localhost:5173/"
echo ""
echo "📋 TESTING CHECKLIST:"
echo ""
echo "STEP 1: Navigate to Dashboard"
echo "  → Open: http://localhost:5173/"
echo "  → Ensure you see invoices in 'Recent Invoices' section"
echo ""
echo "STEP 2: Access Invoice Actions"
echo "  → Find any invoice in the list"
echo "  → Click the three-dot menu (⋮) on the right side"
echo "  → Dropdown menu should appear with multiple options"
echo ""
echo "STEP 3: Click 'View Invoice'"
echo "  → Click on 'View Invoice' (Eye icon)"
echo "  → Page should navigate to ViewInvoice"
echo "  → URL should be: /ViewInvoice?id={some-id}"
echo ""
echo "STEP 4: Verify Invoice Display"
echo "  ✓ Company header with logo/name"
echo "  ✓ Invoice number (e.g., #INV-001)"
echo "  ✓ Client billing information"
echo "  ✓ Invoice items table"
echo "  ✓ Subtotal, tax, and total"
echo "  ✓ Notes section (if applicable)"
echo "  ✓ Banking details (if applicable)"
echo "  ✓ Version history sidebar"
echo ""
echo "STEP 5: Test Action Buttons"
echo "  ✓ Back - returns to previous page"
echo "  ✓ Preview - opens PDF preview"
echo "  ✓ Print - opens print dialog"
echo "  ✓ Download PDF - downloads invoice PDF"
echo "  ✓ Email Client - sends invoice to client"
echo "  ✓ Edit - navigates to edit page (or disabled if locked)"
echo ""
echo "STEP 6: Check Console"
echo "  → Open browser DevTools (F12)"
echo "  → Check Console tab for errors"
echo "  → No errors should appear"
echo ""
echo "================================================"
echo ""
echo "🎯 QUICK TEST SCENARIOS:"
echo ""
echo "1. Test with DRAFT invoice:"
echo "   - View should work"
echo "   - Edit button should be enabled"
echo "   - Email button should work"
echo ""
echo "2. Test with PAID invoice:"
echo "   - View should work"
echo "   - Edit button should be DISABLED"
echo "   - All other actions should work"
echo ""
echo "3. Test with CANCELLED invoice:"
echo "   - View should work"
echo "   - Edit button should be DISABLED"
echo ""
echo "================================================"
echo ""
echo "🔍 THINGS TO VERIFY:"
echo ""
echo "✓ Currency formatting (e.g., R 1,234.56 for ZAR)"
echo "✓ Date formatting (e.g., February 2, 2026)"
echo "✓ All line items display correctly"
echo "✓ Calculations are accurate"
echo "✓ Responsive design on different screen sizes"
echo "✓ No broken images or missing data"
echo "✓ Version history shows changes (if any)"
echo ""
echo "================================================"
echo ""
echo "🐛 COMMON ISSUES TO CHECK:"
echo ""
echo "1. Missing invoice data → Check if invoice exists in DB"
echo "2. Currency not formatting → Verify formatCurrency import"
echo "3. Navigation not working → Check route configuration"
echo "4. Edit button always disabled → Check status logic"
echo "5. Version history empty → Normal if no changes made"
echo ""
echo "================================================"
echo ""
echo "🚀 Ready to test? Open: http://localhost:5173/"
echo ""
echo "Press Ctrl+C to exit this guide"
echo "================================================"

# Keep script running
read -p ""
