#!/bin/bash

# PDF Preview & Download - Quick Test Script
# This script helps you manually test PDF functionality

echo "================================================"
echo "  PDF PREVIEW & DOWNLOAD - TEST GUIDE"
echo "================================================"
echo ""
echo "✅ Server Status: Running at http://localhost:5173/"
echo ""
echo "🔧 FIXES APPLIED:"
echo "  ✓ Fixed formatCurrency imports in all PDF templates"
echo "  ✓ ClassicTemplate.jsx - import fixed"
echo "  ✓ ModernTemplate.jsx - import fixed"
echo "  ✓ MinimalTemplate.jsx - import fixed"
echo "  ✓ BoldTemplate.jsx - import fixed"
echo ""
echo "================================================"
echo ""
echo "📋 QUICK TEST STEPS:"
echo ""
echo "1. PREVIEW PDF FROM DASHBOARD"
echo "   → Open: http://localhost:5173/"
echo "   → Click three-dot menu (⋮) on any invoice"
echo "   → Click 'Preview PDF'"
echo "   → New tab opens with PDF preview"
echo "   → Verify invoice displays correctly"
echo ""
echo "2. DOWNLOAD PDF FROM DASHBOARD"
echo "   → Click three-dot menu (⋮) on any invoice"
echo "   → Click 'Download PDF'"
echo "   → Toast: 'Download started'"
echo "   → New tab opens"
echo "   → Print dialog appears"
echo "   → Save as PDF"
echo ""
echo "3. PREVIEW FROM VIEW INVOICE PAGE"
echo "   → Navigate to View Invoice page"
echo "   → Click 'Preview' button (top action bar)"
echo "   → New tab opens with PDF"
echo "   → Toast: 'Preview opened'"
echo ""
echo "4. DOWNLOAD FROM VIEW INVOICE PAGE"
echo "   → On View Invoice page"
echo "   → Click 'Download PDF' button"
echo "   → Toast: 'Download started'"
echo "   → Print dialog appears"
echo ""
echo "5. PRINT FUNCTIONALITY"
echo "   → On View Invoice page"
echo "   → Click 'Print' button"
echo "   → New window opens"
echo "   → Print dialog auto-opens"
echo ""
echo "================================================"
echo ""
echo "🎨 TEST DIFFERENT TEMPLATES:"
echo ""
echo "To test all templates, go to Settings and change:"
echo "  - Classic Template (default)"
echo "  - Modern Template"
echo "  - Minimal Template"
echo "  - Bold Template"
echo ""
echo "Each template should render correctly with:"
echo "  ✓ Company logo/name"
echo "  ✓ Invoice details"
echo "  ✓ Line items"
echo "  ✓ Totals (subtotal, tax, total)"
echo "  ✓ Banking details (if set)"
echo "  ✓ Notes (if any)"
echo ""
echo "================================================"
echo ""
echo "✅ WHAT TO VERIFY:"
echo ""
echo "Preview PDF:"
echo "  ✓ Opens in new tab"
echo "  ✓ URL: /InvoicePDF?id={invoice_id}"
echo "  ✓ Shows 'Back' and 'Download PDF' buttons"
echo "  ✓ Invoice renders correctly"
echo "  ✓ All data displays"
echo "  ✓ Currency formatted (e.g., R 1,234.56)"
echo "  ✓ Dates formatted (e.g., February 2, 2026)"
echo ""
echo "Download PDF:"
echo "  ✓ Toast notification appears"
echo "  ✓ Opens in new tab with download=true param"
echo "  ✓ Print dialog opens automatically"
echo "  ✓ Can save as PDF"
echo "  ✓ Filename: Invoice-{number}.pdf"
echo "  ✓ PDF content is clean (no buttons)"
echo ""
echo "Print Layout:"
echo "  ✓ No 'Back' button in print view"
echo "  ✓ No 'Download PDF' button in print view"
echo "  ✓ Clean page margins"
echo "  ✓ Content fits on A4"
echo "  ✓ Professional appearance"
echo ""
echo "================================================"
echo ""
echo "🧪 TEST SCENARIOS:"
echo ""
echo "1. Invoice with Tax"
echo "   ✓ Tax rate displays"
echo "   ✓ Tax amount calculated"
echo "   ✓ Total includes tax"
echo ""
echo "2. Invoice with Multiple Items"
echo "   ✓ All items display"
echo "   ✓ Quantities correct"
echo "   ✓ Prices formatted"
echo "   ✓ Totals accurate"
echo ""
echo "3. Invoice with Discount"
echo "   ✓ Discount shows"
echo "   ✓ Percentage/fixed displays"
echo "   ✓ Total reflects discount"
echo ""
echo "4. Invoice with Banking Details"
echo "   ✓ Banking section appears"
echo "   ✓ Bank name"
echo "   ✓ Account details"
echo "   ✓ Routing/SWIFT codes"
echo ""
echo "5. Invoice with Company Logo"
echo "   ✓ Logo displays"
echo "   ✓ Proper size"
echo "   ✓ Good quality"
echo ""
echo "================================================"
echo ""
echo "🐛 COMMON ISSUES TO CHECK:"
echo ""
echo "1. Currency not formatting"
echo "   → FIXED: All templates now use @/utils/currencyCalculations"
echo ""
echo "2. PDF doesn't open"
echo "   → Check browser popup blocker"
echo "   → Check console for errors"
echo ""
echo "3. Print dialog doesn't appear"
echo "   → May take ~500ms to load"
echo "   → Check browser print permissions"
echo ""
echo "4. Download not working"
echo "   → Check browser download settings"
echo "   → Verify download folder permissions"
echo ""
echo "5. Missing data in PDF"
echo "   → Check invoice has all required data"
echo "   → Verify client/company info exists"
echo ""
echo "================================================"
echo ""
echo "📊 EXPECTED BEHAVIOR:"
echo ""
echo "InvoiceActions Dropdown:"
echo "  → 'Preview PDF' - Opens new tab with preview"
echo "  → 'Download PDF' - Opens print dialog"
echo ""
echo "ViewInvoice Page:"
echo "  → 'Preview' button - Opens new tab"
echo "  → 'Download PDF' button - Opens print dialog"
echo "  → 'Print' button - Opens print window"
echo ""
echo "InvoicePDF Page:"
echo "  → Shows invoice in selected template"
echo "  → 'Back' button returns to previous page"
echo "  → 'Download PDF' button opens print dialog"
echo "  → Auto-download (if ?download=true)"
echo ""
echo "================================================"
echo ""
echo "🔍 TESTING URLs:"
echo ""
echo "Dashboard:"
echo "  http://localhost:5173/"
echo ""
echo "View Invoice (replace {id} with actual invoice ID):"
echo "  http://localhost:5173/ViewInvoice?id={id}"
echo ""
echo "PDF Preview (replace {id} with actual invoice ID):"
echo "  http://localhost:5173/InvoicePDF?id={id}"
echo ""
echo "PDF Auto-Download (replace {id} with actual invoice ID):"
echo "  http://localhost:5173/InvoicePDF?id={id}&download=true"
echo ""
echo "================================================"
echo ""
echo "✨ PRO TIPS:"
echo ""
echo "1. Test with real data for best results"
echo "2. Try different invoice amounts to test formatting"
echo "3. Test with/without tax, discount, notes"
echo "4. Check print preview before printing"
echo "5. Test in different browsers"
echo "6. Check responsive design on mobile"
echo ""
echo "================================================"
echo ""
echo "🚀 Ready to test? Open: http://localhost:5173/"
echo ""
echo "Press Ctrl+C to exit this guide"
echo "================================================"

# Keep script running
read -p ""
