#!/bin/bash

# Record Payment & Update Status - Quick Test Script

echo "================================================"
echo "  RECORD PAYMENT & UPDATE STATUS - TEST GUIDE"
echo "================================================"
echo ""
echo "✅ Server Status: Running at http://localhost:5173/"
echo ""
echo "🔧 FIXES APPLIED:"
echo "  ✓ Fixed formatCurrency import in RecordPaymentModal"
echo "  ✓ Verified payment recording logic"
echo "  ✓ Verified manual status update rules"
echo ""
echo "================================================"
echo ""
echo "📋 QUICK TEST STEPS:"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 1: RECORD PARTIAL PAYMENT"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Select Invoice with Outstanding Balance:"
echo "   → Open: http://localhost:5173/"
echo "   → Find invoice with status: sent/viewed/overdue"
echo "   → Note total amount (e.g., R 1,000.00)"
echo ""
echo "2. Open Record Payment Modal:"
echo "   → Click three-dot menu (⋮) on invoice"
echo "   → Click 'Record Payment'"
echo "   → Modal opens: 'Record Payment for Invoice #XXX'"
echo ""
echo "3. Verify Modal Display:"
echo "   ✓ Shows remaining balance in blue box"
echo "   ✓ Amount field with dollar icon"
echo "   ✓ Payment date field (defaults to today)"
echo "   ✓ Payment method field"
echo "   ✓ Reference/Notes field (optional)"
echo ""
echo "4. Enter Partial Payment:"
echo "   → Amount: Enter LESS than total (e.g., 400.00 for 1,000 invoice)"
echo "   → Date: Select payment date"
echo "   → Method: Enter payment method (e.g., 'Bank Transfer')"
echo "   → Notes: Add reference (optional)"
echo ""
echo "5. Validation Checks:"
echo "   ✓ Amount must be > 0"
echo "   ✓ Amount must be ≤ remaining balance"
echo "   ✓ Red error if amount exceeds balance"
echo "   ✓ Button disabled if fields incomplete"
echo ""
echo "6. Click 'Record Payment':"
echo "   → Toast: 'Payment recorded'"
echo "   → Modal closes"
echo "   → Invoice status updates to 'partial_paid'"
echo "   → Remaining balance decreases"
echo ""
echo "7. Verify Invoice Updated:"
echo "   → Status badge shows 'partial paid'"
echo "   → View invoice to see payment history"
echo "   → Version history shows payment record"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 2: RECORD FULL PAYMENT"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Select Invoice:"
echo "   → Choose invoice with remaining balance"
echo "   → Can be new invoice or partially paid one"
echo ""
echo "2. Open Record Payment Modal:"
echo "   → Click ⋮ → 'Record Payment'"
echo "   → Note remaining balance"
echo ""
echo "3. Enter Full Payment:"
echo "   → Amount: Enter EXACT remaining balance"
echo "   → OR enter amount that brings total to 100%"
echo "   → Date: Select date"
echo "   → Method: Enter method"
echo ""
echo "4. Click 'Record Payment':"
echo "   → Payment recorded"
echo "   → Invoice status changes to 'paid' ✓"
echo "   → Badge turns green"
echo ""
echo "5. Verify Paid Status:"
echo "   → Status: 'paid'"
echo "   → Edit button disabled (invoice locked)"
echo "   → Can still view/download/share"
echo "   → Cannot record additional payments"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 3: MULTIPLE PARTIAL PAYMENTS"
echo "═══════════════════════════════════════════════"
echo ""
echo "Example: Invoice total R 1,000.00"
echo ""
echo "1. First Payment (40%):"
echo "   → Record: R 400.00"
echo "   → Status: partial_paid"
echo "   → Remaining: R 600.00"
echo ""
echo "2. Second Payment (30%):"
echo "   → Record: R 300.00"
echo "   → Status: partial_paid"
echo "   → Remaining: R 300.00"
echo ""
echo "3. Final Payment (30%):"
echo "   → Record: R 300.00"
echo "   → Status: paid ✓"
echo "   → Remaining: R 0.00"
echo ""
echo "4. Verify Payment History:"
echo "   → View invoice"
echo "   → Check version history"
echo "   → Should show all 3 payments"
echo "   → Each with date, method, amount"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 4: MANUAL STATUS UPDATE (ADMIN OVERRIDE)"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Open Status Menu:"
echo "   → Click ⋮ on any invoice"
echo "   → Hover over 'Update Status'"
echo "   → Submenu appears with status options"
echo ""
echo "2. Verify Allowed Transitions:"
echo ""
echo "   From DRAFT → Can change to:"
echo "   ✓ Sent"
echo "   ✓ Cancelled"
echo "   ✗ Cannot: viewed, paid, overdue, partial_paid"
echo ""
echo "   From SENT → Can change to:"
echo "   ✓ Viewed"
echo "   ✓ Partial Paid"
echo "   ✓ Paid"
echo "   ✓ Overdue"
echo "   ✓ Cancelled"
echo ""
echo "   From VIEWED → Can change to:"
echo "   ✓ Partial Paid"
echo "   ✓ Paid"
echo "   ✓ Overdue"
echo "   ✓ Cancelled"
echo "   ✗ Cannot: sent, draft"
echo ""
echo "   From OVERDUE → Can change to:"
echo "   ✓ Partial Paid"
echo "   ✓ Paid"
echo "   ✓ Cancelled"
echo "   ✗ Cannot: draft, sent, viewed"
echo ""
echo "   From PARTIAL_PAID → Can change to:"
echo "   ✓ Paid"
echo "   ✓ Cancelled"
echo "   ✗ Cannot: all others"
echo ""
echo "   From PAID → Cannot change"
echo "   ✗ Status is locked"
echo ""
echo "   From CANCELLED → Cannot change"
echo "   ✗ Status is locked"
echo ""
echo "3. Test Valid Status Change:"
echo "   → Select SENT invoice"
echo "   → Click 'Update Status' → 'Mark as Viewed'"
echo "   → Toast: 'Status updated'"
echo "   → Invoice status changes to 'viewed'"
echo "   → Version history updated"
echo ""
echo "4. Test Invalid Status Change:"
echo "   → Select PAID invoice"
echo "   → Try to change status"
echo "   → Options should be disabled"
echo "   → Toast: 'Status change blocked'"
echo "   → Status remains unchanged"
echo ""
echo "5. Test Blocked Transition:"
echo "   → Select VIEWED invoice"
echo "   → Try 'Mark as Sent' (going backwards)"
echo "   → Should be disabled/blocked"
echo "   → Error: Cannot change status"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 5: PAYMENT VALIDATION"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Test Zero Amount:"
echo "   → Enter: 0.00"
echo "   → Error: 'Amount must be greater than 0'"
echo "   → Button disabled"
echo ""
echo "2. Test Negative Amount:"
echo "   → Enter: -100"
echo "   → Error or prevented by input"
echo "   → Button disabled"
echo ""
echo "3. Test Amount > Balance:"
echo "   → Remaining: R 500.00"
echo "   → Enter: R 600.00"
echo "   → Error: 'Amount cannot exceed remaining balance'"
echo "   → Shows red text below field"
echo "   → Button disabled"
echo ""
echo "4. Test Missing Fields:"
echo "   → Leave amount empty"
echo "   → Button disabled"
echo "   → Leave method empty"
echo "   → Button disabled"
echo "   → Fill all required fields"
echo "   → Button enabled"
echo ""
echo "5. Test Date Field:"
echo "   → Future date allowed"
echo "   → Past date allowed"
echo "   → Default: Today"
echo ""
echo "================================================"
echo ""
echo "🎨 VISUAL INDICATORS:"
echo ""
echo "Status Badges:"
echo "  • Draft - Gray"
echo "  • Sent - Blue"
echo "  • Viewed - Purple"
echo "  • Partial Paid - Yellow/Orange"
echo "  • Paid - Green ✓"
echo "  • Overdue - Red"
echo "  • Cancelled - Dark Gray"
echo ""
echo "Payment Modal:"
echo "  • Blue info box - Remaining balance"
echo "  • Red error box - Validation errors"
echo "  • Green checkmark - Valid input"
echo "  • Dollar icon - Amount field"
echo "  • Calendar icon - Date field"
echo "  • Credit card icon - Method field"
echo ""
echo "================================================"
echo ""
echo "✅ WHAT TO VERIFY:"
echo ""
echo "Record Payment:"
echo "  ✓ Modal opens correctly"
echo "  ✓ Shows remaining balance"
echo "  ✓ Validates amount (0 < amount ≤ balance)"
echo "  ✓ Requires date and method"
echo "  ✓ Optional notes field works"
echo "  ✓ Payment recorded successfully"
echo "  ✓ Status updates automatically:"
echo "    - Partial payment → 'partial_paid'"
echo "    - Full payment → 'paid'"
echo "  ✓ Version history updated"
echo "  ✓ Toast notification appears"
echo "  ✓ Remaining balance recalculates"
echo ""
echo "Update Status:"
echo "  ✓ Submenu shows status options"
echo "  ✓ Invalid options disabled"
echo "  ✓ Valid transitions allowed"
echo "  ✓ Blocked transitions prevented"
echo "  ✓ Toast shows error for blocked changes"
echo "  ✓ Version history tracks manual changes"
echo "  ✓ Status badge updates"
echo "  ✓ Edit locked for paid/cancelled"
echo ""
echo "================================================"
echo ""
echo "🧪 TEST SCENARIOS:"
echo ""
echo "Scenario 1: Installment Payments"
echo "  Invoice: R 3,000.00"
echo "  Payment 1: R 1,000.00 → partial_paid"
echo "  Payment 2: R 1,000.00 → partial_paid"
echo "  Payment 3: R 1,000.00 → paid ✓"
echo ""
echo "Scenario 2: Overpayment Prevention"
echo "  Remaining: R 500.00"
echo "  Try: R 600.00"
echo "  Result: Error, cannot exceed balance"
echo ""
echo "Scenario 3: Status Override"
echo "  Invoice: sent (not actually viewed)"
echo "  Admin: Marks as 'viewed' manually"
echo "  Result: Status updated, history logged"
echo ""
echo "Scenario 4: Payment Before Full Amount"
echo "  Invoice: R 1,000.00 (sent)"
echo "  Payment: R 999.99"
echo "  Result: partial_paid (not paid)"
echo "  Remaining: R 0.01"
echo ""
echo "Scenario 5: Cancelled Invoice"
echo "  Invoice: partial_paid"
echo "  Admin: Changes to 'cancelled'"
echo "  Result: Status locked, cannot edit"
echo ""
echo "================================================"
echo ""
echo "🐛 COMMON ISSUES TO CHECK:"
echo ""
echo "1. Payment not recording"
echo "   → Check all required fields filled"
echo "   → Verify amount is valid"
echo "   → Check console for errors"
echo ""
echo "2. Status not updating"
echo "   → Verify transition is allowed"
echo "   → Check current status"
echo "   → Review manual transition rules"
echo ""
echo "3. Currency not formatting"
echo "   → FIXED: Now uses @/utils/currencyCalculations"
echo "   → Verify in modal display"
echo ""
echo "4. Balance calculation wrong"
echo "   → Check all payments array"
echo "   → Verify total_amount field"
echo "   → Review payment amounts"
echo ""
echo "5. Version history not updating"
echo "   → Check onActionSuccess callback"
echo "   → Verify history entry creation"
echo "   → Refresh invoice view"
echo ""
echo "================================================"
echo ""
echo "📊 EXPECTED BEHAVIOR:"
echo ""
echo "Payment Recording Flow:"
echo "  1. Click 'Record Payment'"
echo "  2. Modal shows remaining balance"
echo "  3. Fill amount, date, method"
echo "  4. Click 'Record Payment' button"
echo "  5. Toast confirms success"
echo "  6. Status auto-updates:"
echo "     - < 100% → partial_paid"
echo "     - = 100% → paid"
echo "  7. Version history updated"
echo "  8. Invoice refreshes"
echo ""
echo "Manual Status Update Flow:"
echo "  1. Click ⋮ → 'Update Status'"
echo "  2. Submenu shows allowed statuses"
echo "  3. Click desired status"
echo "  4. If allowed:"
echo "     - Status updates"
echo "     - Toast: 'Status updated'"
echo "     - History logged"
echo "  5. If blocked:"
echo "     - Toast: 'Status change blocked'"
echo "     - Status unchanged"
echo ""
echo "================================================"
echo ""
echo "🔍 TESTING URLS:"
echo ""
echo "Dashboard:"
echo "  http://localhost:5173/"
echo ""
echo "View Invoice (check payment history):"
echo "  http://localhost:5173/ViewInvoice?id={id}"
echo ""
echo "================================================"
echo ""
echo "✨ PRO TIPS:"
echo ""
echo "1. Test with invoices of different amounts"
echo "2. Try decimal amounts (e.g., 123.45)"
echo "3. Test multiple payments on same invoice"
echo "4. Verify payment method field accepts any text"
echo "5. Check version history after each action"
echo "6. Test with different currencies (ZAR, USD, EUR)"
echo "7. Verify locked status (paid/cancelled) cannot be changed"
echo "8. Test that Edit button disables for paid invoices"
echo ""
echo "================================================"
echo ""
echo "🚀 Ready to test? Open: http://localhost:5173/"
echo ""
echo "Press Ctrl+C to exit this guide"
echo "================================================"

# Keep script running
read -p ""
