#!/bin/bash

# Email to Client & Get Share Link - Quick Test Script

echo "================================================"
echo "  EMAIL & SHARE LINK - TEST GUIDE"
echo "================================================"
echo ""
echo "✅ Server Status: Running at http://localhost:5173/"
echo ""
echo "🔧 FIXES APPLIED:"
echo "  ✓ Fixed formatCurrency import in EmailPreviewModal"
echo "  ✓ Fixed SendEmail import in ManualShareModal"
echo "  ✓ Updated to use breakApi.integrations.Core.SendEmail"
echo ""
echo "================================================"
echo ""
echo "📋 QUICK TEST STEPS:"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 1: GET SHAREABLE LINK"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. From Dashboard:"
echo "   → Open: http://localhost:5173/"
echo "   → Click three-dot menu (⋮) on any invoice"
echo "   → Click 'Get Share Link'"
echo "   → Modal opens with public link"
echo ""
echo "2. Verify Share Modal:"
echo "   ✓ Public link displays in input field"
echo "   ✓ Format: /PublicInvoice?token={uuid}"
echo "   ✓ Copy button visible"
echo "   ✓ Email section visible below"
echo ""
echo "3. Copy Link:"
echo "   → Click 'Copy' button"
echo "   → Button changes to 'Copied!' (green checkmark)"
echo "   → Paste in new tab/browser"
echo "   → Public invoice page opens (no login needed)"
echo ""
echo "4. Send Email from Share Modal:"
echo "   → Fill in recipient email"
echo "   → Fill in subject"
echo "   → (Optional) Add personal message"
echo "   → Click 'Send Email'"
echo "   → Alert: 'Email sent successfully!'"
echo "   → Modal closes"
echo "   → Invoice marked as sent (if draft)"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 2: EMAIL TO CLIENT (WITH PREVIEW)"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. From Dashboard:"
echo "   → Click three-dot menu (⋮) on any invoice"
echo "   → Click 'Email to Client'"
echo "   → EmailPreviewModal opens"
echo ""
echo "2. Verify Email Preview Modal:"
echo "   ✓ Title: 'Email & PDF Preview'"
echo "   ✓ Shows: To: {client.email}"
echo "   ✓ Shows: Subject: Invoice {number} from {company}"
echo "   ✓ Badge: '🔗 Download Link Included'"
echo "   ✓ Two tabs: 'Email Preview' and 'PDF Preview'"
echo ""
echo "3. Email Preview Tab:"
echo "   → Check email content displays"
echo "   → Purple gradient header"
echo "   → Company name and invoice number"
echo "   → Invoice summary box with:"
echo "     • Invoice number"
echo "     • Project title"
echo "     • Amount due (formatted currency)"
echo "     • Due date"
echo "   → 'View & Download Invoice' button (purple)"
echo "   → Professional HTML formatting"
echo ""
echo "4. PDF Preview Tab:"
echo "   → Click 'PDF Preview' tab"
echo "   → Shows invoice layout:"
echo "     • Company header"
echo "     • Invoice number"
echo "     • Bill To section"
echo "     • Line items table"
echo "     • Totals (subtotal, tax, total)"
echo "     • Banking info (if configured)"
echo "     • Notes (if any)"
echo ""
echo "5. Send Email:"
echo "   → Click 'Send Email with Download Link'"
echo "   → Button shows 'Sending...'"
echo "   → Toast notification on success"
echo "   → Modal closes"
echo "   → Status updates to 'sent' (if draft)"
echo ""
echo "═══════════════════════════════════════════════"
echo "TEST 3: PUBLIC INVOICE ACCESS"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Get Public Link:"
echo "   → Use 'Get Share Link' option"
echo "   → Copy the generated URL"
echo ""
echo "2. Open in Incognito/Private Window:"
echo "   → Paste URL"
echo "   → Public invoice page loads"
echo "   → No login required"
echo ""
echo "3. Verify Public Page:"
echo "   ✓ Company logo/name"
echo "   ✓ Invoice number"
echo "   ✓ Client information"
echo "   ✓ All line items"
echo "   ✓ Totals"
echo "   ✓ Banking details"
echo "   ✓ Download PDF button works"
echo ""
echo "================================================"
echo ""
echo "🧪 TEST DIFFERENT SCENARIOS:"
echo ""
echo "1. DRAFT INVOICE"
echo "   → Get share link - works"
echo "   → Send email - status changes to 'sent'"
echo "   → Share modal offers to mark as sent"
echo ""
echo "2. INVOICE WITH TAX"
echo "   → Email preview shows tax"
echo "   → PDF preview shows tax calculation"
echo "   → Public view displays tax"
echo ""
echo "3. INVOICE WITH DISCOUNT"
echo "   → Shows in all previews"
echo "   → Total reflects discount"
echo ""
echo "4. INVOICE WITH NOTES"
echo "   → Notes in email preview"
echo "   → Notes in PDF preview"
echo "   → Notes on public page"
echo ""
echo "5. INVOICE WITH BANKING DETAILS"
echo "   → Banking info in email"
echo "   → Banking info in PDF"
echo "   → Banking info on public page"
echo ""
echo "================================================"
echo ""
echo "✅ WHAT TO VERIFY:"
echo ""
echo "Share Link:"
echo "  ✓ Unique token generated (UUID format)"
echo "  ✓ Same token reused for same invoice"
echo "  ✓ Copy to clipboard works"
echo "  ✓ Public URL format correct"
echo "  ✓ Public page accessible"
echo "  ✓ No login required"
echo ""
echo "Email to Client:"
echo "  ✓ Email preview modal opens"
echo "  ✓ Shows recipient and subject"
echo "  ✓ Email tab shows HTML preview"
echo "  ✓ PDF tab shows invoice layout"
echo "  ✓ All data formatted correctly"
echo "  ✓ Currency formatted (e.g., R 1,234.56)"
echo "  ✓ Dates formatted (e.g., Feb 2, 2026)"
echo "  ✓ Send button works"
echo "  ✓ Toast notifications appear"
echo "  ✓ Status updates (draft → sent)"
echo ""
echo "Mark as Sent:"
echo "  ✓ Sends email from share modal"
echo "  ✓ Updates invoice status"
echo "  ✓ Records sent_to_email field"
echo "  ✓ Adds to version history"
echo ""
echo "================================================"
echo ""
echo "🐛 COMMON ISSUES TO CHECK:"
echo ""
echo "1. Copy button not working"
echo "   → Check browser clipboard permissions"
echo "   → Try different browser"
echo ""
echo "2. Email preview not loading"
echo "   → Verify company data exists"
echo "   → Check console for errors"
echo "   → Verify client has email"
echo ""
echo "3. Public link shows 404"
echo "   → Verify token saved to invoice"
echo "   → Check URL format"
echo "   → Verify PublicInvoice route exists"
echo ""
echo "4. Email not sending"
echo "   → Check email integration setup"
echo "   → Verify API connection"
echo "   → Check console for errors"
echo ""
echo "5. Status not updating"
echo "   → Verify onActionSuccess callback"
echo "   → Check version_history updates"
echo "   → Refresh page to verify"
echo ""
echo "================================================"
echo ""
echo "📊 EXPECTED BEHAVIOR:"
echo ""
echo "Get Share Link Flow:"
echo "  1. Click 'Get Share Link'"
echo "  2. Token generated (or reused)"
echo "  3. Modal opens with URL"
echo "  4. Can copy OR email"
echo "  5. Public link works without login"
echo ""
echo "Email to Client Flow:"
echo "  1. Click 'Email to Client'"
echo "  2. Preview modal loads"
echo "  3. Shows email & PDF tabs"
echo "  4. Click send"
echo "  5. Email sent with link"
echo "  6. Client receives email"
echo "  7. Can view/download invoice"
echo ""
echo "================================================"
echo ""
echo "🔍 TESTING URLs:"
echo ""
echo "Dashboard:"
echo "  http://localhost:5173/"
echo ""
echo "View Invoice (replace {id}):"
echo "  http://localhost:5173/ViewInvoice?id={id}"
echo ""
echo "Public Invoice (replace {token}):"
echo "  http://localhost:5173/PublicInvoice?token={token}"
echo ""
echo "================================================"
echo ""
echo "✨ PRO TIPS:"
echo ""
echo "1. Test with real email to verify delivery"
echo "2. Check email spam folder if not received"
echo "3. Test share link in incognito mode"
echo "4. Verify token persists across sessions"
echo "5. Test mark as sent with draft invoices"
echo "6. Check version history after actions"
echo "7. Test copy functionality in different browsers"
echo "8. Verify public page works on mobile"
echo ""
echo "================================================"
echo ""
echo "📧 EMAIL CONTENT CHECKLIST:"
echo ""
echo "Email Should Include:"
echo "  ✓ Purple gradient header"
echo "  ✓ Company name"
echo "  ✓ Invoice number"
echo "  ✓ Invoice summary box"
echo "  ✓ Amount due (formatted)"
echo "  ✓ Due date"
echo "  ✓ 'View & Download Invoice' button"
echo "  ✓ Professional styling"
echo "  ✓ Footer with company info"
echo ""
echo "================================================"
echo ""
echo "🚀 Ready to test? Open: http://localhost:5173/"
echo ""
echo "Press Ctrl+C to exit this guide"
echo "================================================"

# Keep script running
read -p ""
