import React, { useState, useEffect, useCallback } from "react";
import { Invoice, Client, BankingDetail, Service, Quote, User, RecurringInvoice } from "@/api/entities"; // Added User import
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, Copy } from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import { useToast } from "@/components/ui/use-toast";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";
import { InvoiceNumberGenerator } from "@/services/InvoiceNumberGenerator";
import { createHistoryEntry } from "@/utils/invoiceHistory";
import { logInvoiceCreated } from "@/utils/auditLogger";

import ProjectDetails from "../components/invoice/ProjectDetails";
import InvoicePreview from "../components/invoice/InvoicePreview";

// Helper function to generate payment terms text
const getDefaultPaymentTermsText = (terms, days) => {
    if (!terms || terms === 'net_30') {
        return `Payment is due within 30 days of invoice date.\n\nLate payments may incur a 1.5% monthly service charge.\nAll payments should be made to the banking details provided above.`;
    }
    
    if (terms === 'due_on_receipt') {
        return `Payment is due immediately upon receipt of this invoice.\n\nPlease remit payment to the banking details provided above.\nThank you for your prompt payment.`;
    }
    
    const termDays = terms === 'custom' ? (days || 30) : parseInt(terms.split('_')[1] || 30);
    
    return `Payment is due within ${termDays} days of invoice date.\n\nLate payments may incur a 1.5% monthly service charge.\nAll payments should be made to the banking details provided above.`;
};

export default function CreateInvoice() {
    const navigate = useNavigate();
    const location = useLocation();
    const { toast } = useToast();
    const [clients, setClients] = useState([]);
    const [bankingDetails, setBankingDetails] = useState([]);
    const [services, setServices] = useState([]);
    const [sourceQuoteId, setSourceQuoteId] = useState(null); // To track the original quote
    const [autoGeneratedInvoiceNumber, setAutoGeneratedInvoiceNumber] = useState("");
    const defaultDeliveryDate = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
        .toISOString()
        .split('T')[0];
    const [invoiceData, setInvoiceData] = useState({
        client_id: "",
        project_title: "",
        project_description: "",
        reference_number: "", // PO/Reference Number
        items: [],
        subtotal: 0,
        tax_rate: 0,
        tax_amount: 0,
        total_amount: 0,
        invoice_date: new Date().toISOString().split('T')[0], // Invoice/Issue date - editable
        delivery_date: defaultDeliveryDate, // Due date - editable
        delivery_address: "",
        banking_detail_id: "",
        notes: "",
        terms_conditions: ""
    });

    // Recurring state
    const [isRecurring, setIsRecurring] = useState(false);
    const [frequency, setFrequency] = useState("monthly");
    const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
    const [endDate, setEndDate] = useState("");
    const [profileName, setProfileName] = useState("");

    const loadInitialData = useCallback(async () => {
        try {
            const [clientsData, bankingData, servicesData] = await Promise.all([
                Client.list("-created_date"),
                BankingDetail.list("-created_date"),
                Service.list("-created_date")
            ]);
            setClients(clientsData);
            setBankingDetails(bankingData);
            setServices(servicesData);

            // Check if converting from a quote
            const params = new URLSearchParams(location.search);
            const quoteId = params.get('quoteId');
            if (quoteId) {
                setSourceQuoteId(quoteId); // Store the quote ID
                const quote = await Quote.get(quoteId);
                setInvoiceData(prev => ({
                    ...prev,
                    client_id: quote.client_id,
                    project_title: quote.project_title,
                    project_description: quote.project_description,
                    reference_number: quote.reference_number || "",
                    items: quote.items,
                    subtotal: quote.subtotal,
                    tax_rate: quote.tax_rate,
                    tax_amount: quote.tax_amount,
                    total_amount: quote.total_amount,
                    notes: quote.notes,
                    terms_conditions: quote.terms_conditions || prev.terms_conditions,
                    delivery_date: quote.valid_until || prev.delivery_date
                }));
            }

        } catch (error) {
            console.error("Error loading data:", error);
        }
    }, [location.search]); // Depend on location.search because it's used inside the function

    useEffect(() => {
        loadInitialData();
    }, [loadInitialData]); // Depend on loadInitialData to re-run when it changes (which it won't unless location.search changes)

    // Generate invoice number and populate payment terms when client is selected
    useEffect(() => {
        if (invoiceData.client_id) {
            const selectedClient = clients.find(c => c.id === invoiceData.client_id);
            if (selectedClient) {
                const newInvoiceNumber = InvoiceNumberGenerator.generateInvoiceNumber(selectedClient.name);
                setAutoGeneratedInvoiceNumber(newInvoiceNumber);
                
                // Auto-populate payment terms from client defaults
                if (selectedClient.payment_terms && !invoiceData.terms_conditions) {
                    const termsText = getDefaultPaymentTermsText(
                        selectedClient.payment_terms, 
                        selectedClient.payment_terms_days
                    );
                    setInvoiceData(prev => ({
                        ...prev,
                        terms_conditions: termsText
                    }));
                }
            }
        }
    }, [invoiceData.client_id, clients]);

    const calculatePayments = (totalAmount) => {
        const upfront = totalAmount * 0.5;
        const remaining = totalAmount - upfront;
        const milestone = remaining * 0.5;
        const final = remaining * 0.5;
        
        return { upfront, milestone, final };
    };

    const handleCreateInvoice = async (saveAsDraft = true) => {
        try {
            const payments = calculatePayments(invoiceData.total_amount);
            const invoiceDate = new Date(invoiceData.invoice_date);
            const deliveryDate = new Date(invoiceData.delivery_date);
            const milestoneDate = new Date(deliveryDate);
            milestoneDate.setDate(milestoneDate.getDate() - 30);
            const finalDate = new Date(deliveryDate);
            finalDate.setDate(finalDate.getDate() + 30);

            // Use the pre-generated invoice number
            const invoiceNumber = autoGeneratedInvoiceNumber || InvoiceNumberGenerator.generateInvoiceNumber(
                clients.find(c => c.id === invoiceData.client_id)?.name || "Client"
            );

            // Get current user data to cache in invoice
            const currentUser = await User.me();

            const status = saveAsDraft ? 'draft' : 'sent';
            const historyEntry = createHistoryEntry({
                action: saveAsDraft ? 'create_draft' : 'create_sent',
                summary: saveAsDraft ? 'Draft created' : 'Invoice created and sent',
                changes: [],
                meta: { status },
            });

            const newInvoice = await Invoice.create({
                ...invoiceData,
                invoice_number: invoiceNumber,
                reference_number: invoiceData.reference_number || undefined,
                created_date: invoiceDate.toISOString().split('T')[0], // Store the invoice date
                upfront_payment: payments.upfront,
                milestone_payment: payments.milestone,
                final_payment: payments.final,
                milestone_date: milestoneDate.toISOString().split('T')[0],
                final_date: finalDate.toISOString().split('T')[0],
                status,
                sent_date: saveAsDraft ? null : new Date().toISOString(),
                public_share_token: crypto.randomUUID(),
                version_history: [historyEntry],
                // Cache owner data for public viewing
                owner_company_name: currentUser.company_name || currentUser.full_name,
                owner_company_address: currentUser.company_address || '',
                owner_logo_url: currentUser.logo_url || '',
                owner_email: currentUser.email || '',
                owner_currency: currentUser.currency || 'ZAR'
            });

            // Log the invoice creation
            const clientName = clients.find(c => c.id === invoiceData.client_id)?.name || "Unknown";
            logInvoiceCreated(
              newInvoice.id,
              invoiceNumber,
              clientName,
              invoiceData.total_amount,
              currentUser.id,
              currentUser.full_name
            );

            // Handle recurring profile creation
            if (isRecurring && profileName) {
                // Remove calculated fields from template
                const { subtotal, tax_amount, total_amount, ...template } = invoiceData;
                
                await RecurringInvoice.create({
                    profile_name: profileName,
                    client_id: invoiceData.client_id,
                    invoice_template: template,
                    frequency,
                    start_date: startDate,
                    end_date: endDate || null,
                    next_generation_date: startDate, 
                    status: 'active',
                });
            }

            // If the invoice was created from a quote, update the quote's status
            if (sourceQuoteId) {
                await Quote.update(sourceQuoteId, { status: 'accepted' });
            }

            // Show success notification
            toast({
                title: saveAsDraft ? "✓ Draft Saved" : "✓ Invoice Sent",
                description: saveAsDraft 
                    ? `Invoice ${invoiceNumber} has been saved as draft.`
                    : `Invoice ${invoiceNumber} has been sent to client.`,
                variant: "success"
            });

            // Navigate after a short delay to allow user to see the notification
            setTimeout(() => {
                navigate(createPageUrl("Invoices"));
            }, 1500);
        } catch (error) {
            console.error("Error creating invoice:", error);
            toast({
                title: "✗ Error",
                description: "Failed to create invoice. Please try again.",
                variant: "destructive"
            });
        }
    };

    return (
        <div className="min-h-screen bg-slate-100 p-4 sm:p-6">
            <div className="max-w-4xl mx-auto">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="flex items-center gap-4 mb-8"
                >
                    <Button
                        variant="outline"
                        size="icon"
                        onClick={() => navigate(createPageUrl("Dashboard"))}
                        className="rounded-lg border-gray-200 hover:bg-gray-50"
                    >
                        <ArrowLeft className="w-4 h-4" />
                    </Button>
                    <div>
                        <h1 className="text-xl sm:text-2xl font-semibold text-gray-900">Create New Invoice</h1>
                        <p className="text-sm sm:text-base text-gray-600 mt-1">Professional invoicing with itemized services</p>
                    </div>
                </motion.div>

                {/* Invoice Number Preview */}
                {autoGeneratedInvoiceNumber && (
                    <motion.div
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3 }}
                        className="mb-6"
                    >
                        <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200">
                            <CardContent className="p-4">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-xs font-medium text-blue-600 uppercase tracking-wide">Auto-Generated Invoice Number</p>
                                        <p className="text-lg font-semibold text-blue-900 mt-1 font-mono">{autoGeneratedInvoiceNumber}</p>
                                    </div>
                                    <Button
                                        size="sm"
                                        variant="outline"
                                        onClick={() => {
                                            navigator.clipboard.writeText(autoGeneratedInvoiceNumber);
                                            toast({
                                                title: "Copied",
                                                description: "Invoice number copied to clipboard",
                                                duration: 2000
                                            });
                                        }}
                                        className="border-blue-200 hover:bg-blue-100"
                                    >
                                        <Copy className="w-4 h-4" />
                                    </Button>
                                </div>
                            </CardContent>
                        </Card>
                    </motion.div>
                )}
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3 }}
                    className="space-y-6"
                >
                    <ProjectDetails
                        invoiceData={invoiceData}
                        setInvoiceData={setInvoiceData}
                        clients={clients}
                        setClients={setClients}
                        bankingDetails={bankingDetails}
                        setBankingDetails={setBankingDetails}
                        services={services}
                        setServices={setServices}
                        isRecurring={false}
                        showNextButton={false}
                    />

                    <InvoicePreview
                        invoiceData={invoiceData}
                        clients={clients}
                        bankingDetails={bankingDetails}
                        onCreate={handleCreateInvoice}
                        showBack={false}
                        // Pass recurring props
                        isRecurring={isRecurring}
                        setIsRecurring={setIsRecurring}
                        frequency={frequency}
                        setFrequency={setFrequency}
                        startDate={startDate}
                        setStartDate={setStartDate}
                        endDate={endDate}
                        setEndDate={setEndDate}
                        profileName={profileName}
                        setProfileName={setProfileName}
                    />
                </motion.div>
            </div>
        </div>
    );
}