/**
 * Paidly-branded authentication emails — one layout for:
 *  - the Supabase Auth email templates (supabase/templates/*.html, generated by
 *    scripts/generate-auth-email-templates.mjs; Supabase still sends them and owns the tokens), and
 *  - the welcome email Paidly sends itself through the existing Resend transport (sendHtmlEmail).
 *
 * Brand: the platform mailer palette (server/src/adminPlatformMailerTemplate.js) and the Paidly mark
 * (public/email/paidly-logo.png — PNG because Gmail/Outlook do not render SVG).
 * Customer-facing copy never mentions the auth provider.
 */

const ACCENT = "#f24e00";
const INK = "#0f172a";
const BODY = "#334155";
const MUTED = "#64748b";
const OUTER_BG = "#f1f5f9";
const FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif";
const SUPPORT_EMAIL = "support@paidly.co.za";

export const PAIDLY_EMAIL_LOGO_PATH = "/email/paidly-logo.png";

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Responsive, table-based email (works in Gmail, Outlook, Apple Mail; full-width CTA on phones).
 * `href`, `logoUrl` and `appOrigin` may be Supabase template expressions ({{ .SiteURL }} …), which is
 * why they are inserted as given — callers pass only trusted values.
 * `fallbackLink` prints the CTA URL as text for clients that block buttons.
 * @param {{ title: string, preheader: string, heading: string, paragraphs: string[], cta: { label: string, href: string },
 *   extraHtml?: string, note?: string, fallbackLink?: boolean, logoUrl: string, appOrigin: string }} opts
 */
export function renderPaidlyEmail({ title, preheader, heading, paragraphs, cta, extraHtml = "", note = "", fallbackLink = false, logoUrl, appOrigin }) {
  const paras = paragraphs
    .map(
      (p, i) =>
        `<p style="margin:0 0 ${i === paragraphs.length - 1 && !extraHtml ? 24 : 14}px;font-size:15px;line-height:1.65;color:${BODY};">${escapeHtml(p)}</p>`
    )
    .join("\n              ");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light only">
  <meta name="supported-color-schemes" content="light">
  <title>${escapeHtml(title)}</title>
  <style>
    @media only screen and (max-width: 600px) {
      .outer { padding: 20px 12px !important; }
      .card { padding: 30px 22px !important; }
      .cta { width: 100% !important; }
      .cta a { display: block !important; text-align: center !important; }
    }
  </style>
</head>
<body style="margin:0;padding:0;background:${OUTER_BG};font-family:${FONT};color:${INK};">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;font-size:1px;line-height:1px;">${escapeHtml(preheader)}</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${OUTER_BG};font-family:${FONT};color:${INK};">
    <tr>
      <td class="outer" align="center" style="padding:36px 16px;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;">
          <tr>
            <td style="padding:0 4px 18px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="vertical-align:middle;padding-right:10px;">
                    <img src="${logoUrl}" width="36" height="36" alt="Paidly" style="display:block;width:36px;height:36px;border:0;border-radius:8px;">
                  </td>
                  <td style="vertical-align:middle;font-size:20px;line-height:1;font-weight:700;letter-spacing:-0.02em;color:${INK};">Paidly</td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td class="card" style="background:#ffffff;border-radius:14px;border-top:4px solid ${ACCENT};padding:38px 34px 28px;">
              <h1 style="margin:0 0 16px;font-size:24px;line-height:1.3;font-weight:700;letter-spacing:-0.02em;color:${INK};">${escapeHtml(heading)}</h1>
              ${paras}
              ${extraHtml}
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="cta" style="margin:0 0 26px;">
                <tr>
                  <td style="border-radius:9px;background:${ACCENT};">
                    <a href="${cta.href}" target="_blank" style="display:inline-block;padding:14px 28px;font-size:15px;line-height:1;font-weight:600;color:#ffffff;text-decoration:none;border-radius:9px;">${escapeHtml(cta.label)}</a>
                  </td>
                </tr>
              </table>
              ${
                fallbackLink
                  ? `<p style="margin:0 0 8px;font-size:12px;line-height:1.5;color:${MUTED};">Button not working?</p>
              <p style="margin:0 0 24px;font-size:12px;line-height:1.5;word-break:break-all;"><a href="${cta.href}" target="_blank" style="color:${ACCENT};text-decoration:underline;">${cta.href}</a></p>`
                  : ""
              }
              ${
                note
                  ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #e2e8f0;">
                <tr>
                  <td style="padding-top:18px;">
                    <p style="margin:0;font-size:13px;line-height:1.6;color:${MUTED};">${escapeHtml(note)}</p>
                  </td>
                </tr>
              </table>`
                  : ""
              }
            </td>
          </tr>
          <tr>
            <td style="padding:20px 8px 0;text-align:center;font-size:12px;line-height:1.6;color:#94a3b8;">
              Paidly · Invoicing, payments and payroll for South African businesses<br>
              Questions? <a href="mailto:${SUPPORT_EMAIL}" style="color:${MUTED};text-decoration:underline;">${SUPPORT_EMAIL}</a> ·
              <a href="${appOrigin}" target="_blank" style="color:${MUTED};text-decoration:underline;">paidly.co.za</a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;
}

// ── Supabase Auth templates (Go template variables are filled in by Supabase) ──────────────

const SUPABASE_LOGO = `{{ .SiteURL }}${PAIDLY_EMAIL_LOGO_PATH}`;

/**
 * Confirm signup. The link goes to Paidly's /auth/verified (the emailRedirectTo, falling back to the
 * Site URL), which calls supabase.auth.verifyOtp({ token_hash, type: "email" }) — Supabase verifies the
 * token; Paidly only shows the result. Works on any device (no PKCE verifier needed) and a link
 * scanner that merely fetches the page cannot spend the token.
 */
export const CONFIRM_SIGNUP_SUBJECT = "Confirm your Paidly email";
export function confirmSignupTemplate() {
  return renderPaidlyEmail({
    title: CONFIRM_SIGNUP_SUBJECT,
    preheader: "Confirm your email address to activate your Paidly account.",
    heading: "Confirm your email",
    paragraphs: ["Welcome to Paidly.", "Please confirm your email address to activate your Paidly account."],
    cta: { label: "Confirm Email", href: "{{ .RedirectTo }}?token_hash={{ .TokenHash }}&type=email" },
    fallbackLink: true,
    note: "If you didn't create a Paidly account, you can safely ignore this email.",
    logoUrl: SUPABASE_LOGO,
    appOrigin: "{{ .SiteURL }}",
  });
}

/** Other auth emails keep Supabase's own link ({{ .ConfirmationURL }}) — only the branding changes. */
export const RESET_PASSWORD_SUBJECT = "Reset your Paidly password";
export function resetPasswordTemplate() {
  return renderPaidlyEmail({
    title: RESET_PASSWORD_SUBJECT,
    preheader: "Reset the password for your Paidly account.",
    heading: "Reset your password",
    paragraphs: ["We received a request to reset the password for your Paidly account."],
    cta: { label: "Reset Password", href: "{{ .ConfirmationURL }}" },
    fallbackLink: true,
    note: "If you didn't ask to reset your password, you can safely ignore this email — your password stays the same.",
    logoUrl: SUPABASE_LOGO,
    appOrigin: "{{ .SiteURL }}",
  });
}

export const MAGIC_LINK_SUBJECT = "Your Paidly sign-in link";
export function magicLinkTemplate() {
  return renderPaidlyEmail({
    title: MAGIC_LINK_SUBJECT,
    preheader: "Sign in to Paidly with one click.",
    heading: "Sign in to Paidly",
    paragraphs: ["Use the button below to sign in to your Paidly account. The link can be used once."],
    cta: { label: "Sign In", href: "{{ .ConfirmationURL }}" },
    fallbackLink: true,
    note: "If you didn't request this link, you can safely ignore this email.",
    logoUrl: SUPABASE_LOGO,
    appOrigin: "{{ .SiteURL }}",
  });
}

export const CHANGE_EMAIL_SUBJECT = "Confirm your new Paidly email";
export function changeEmailTemplate() {
  return renderPaidlyEmail({
    title: CHANGE_EMAIL_SUBJECT,
    preheader: "Confirm the new email address for your Paidly account.",
    heading: "Confirm your new email address",
    paragraphs: ["Please confirm this email address for your Paidly account."],
    cta: { label: "Confirm Email", href: "{{ .ConfirmationURL }}" },
    fallbackLink: true,
    note: "If you didn't request this change, contact your Paidly administrator or support.",
    logoUrl: SUPABASE_LOGO,
    appOrigin: "{{ .SiteURL }}",
  });
}

export const INVITE_SUBJECT = "You've been invited to Paidly";
export function inviteTemplate() {
  return renderPaidlyEmail({
    title: INVITE_SUBJECT,
    preheader: "Accept your invitation to Paidly.",
    heading: "You've been invited to Paidly",
    paragraphs: ["You've been invited to join a workspace on Paidly. Accept the invitation to set up your account."],
    cta: { label: "Accept Invitation", href: "{{ .ConfirmationURL }}" },
    fallbackLink: true,
    note: "If you weren't expecting this invitation, you can safely ignore this email.",
    logoUrl: SUPABASE_LOGO,
    appOrigin: "{{ .SiteURL }}",
  });
}

/** Files written to supabase/templates (keep config.toml [auth.email.template.*] in step). */
export const SUPABASE_AUTH_TEMPLATE_FILES = Object.freeze({
  "confirm-signup.html": confirmSignupTemplate,
  "reset-password.html": resetPasswordTemplate,
  "magic-link.html": magicLinkTemplate,
  "change-email.html": changeEmailTemplate,
  "invite.html": inviteTemplate,
});

/** docs/EMAIL_CONFIRMATION_TEMPLATE.html — the Confirm signup template with paste instructions. */
export function confirmSignupDocFile() {
  return `<!-- Paidly — Confirm signup email (generated by scripts/generate-auth-email-templates.mjs; do not edit by hand) -->
<!-- Supabase Dashboard → Authentication → Emails → Templates → Confirm signup -->
<!-- Subject: ${CONFIRM_SIGNUP_SUBJECT} -->
<!-- Paste everything below. Requires Redirect URLs to include <site>/auth/verified (see docs/AUTH_EMAIL_BRANDING.md). -->
${confirmSignupTemplate()}`;
}

// ── Welcome email (sent by Paidly via Resend) ────────────────────────────────────────────

export const WELCOME_SUBJECT = "Welcome to Paidly";

/** @param {{ appOrigin: string, name?: string | null }} opts */
export function buildWelcomeEmail({ appOrigin, name = null }) {
  const origin = String(appOrigin || "https://www.paidly.co.za").replace(/\/$/, "");
  const steps = [
    "Set up your business profile",
    "Add your clients",
    "Create your first invoice",
    "Explore your Paidly workspace",
  ];
  const list = `<p style="margin:6px 0 8px;font-family:${FONT};font-size:14px;font-weight:700;color:${INK};">Get started with Paidly</p>
              <ol style="margin:0 0 20px;padding-left:20px;font-family:${FONT};font-size:15px;line-height:1.7;color:${BODY};">
                ${steps.map((s) => `<li>${escapeHtml(s)}</li>`).join("\n                ")}
              </ol>`;
  const greeting = name ? `Hi ${String(name).trim().split(/\s+/)[0]},` : null;
  const html = renderPaidlyEmail({
    title: WELCOME_SUBJECT,
    preheader: "Your Paidly account is ready.",
    heading: "Welcome to Paidly",
    paragraphs: [
      ...(greeting ? [greeting] : []),
      "Your email has been verified and your Paidly account is ready.",
      "Start by setting up your business, adding your clients and creating your first invoice.",
    ],
    extraHtml: list,
    cta: { label: "Get Started", href: escapeHtml(`${origin}/Dashboard`) },
    logoUrl: escapeHtml(`${origin}${PAIDLY_EMAIL_LOGO_PATH}`),
    appOrigin: escapeHtml(origin),
  });
  const text = [
    "Welcome to Paidly",
    "",
    ...(greeting ? [greeting, ""] : []),
    "Your email has been verified and your Paidly account is ready.",
    "Start by setting up your business, adding your clients and creating your first invoice.",
    "",
    "Get started with Paidly",
    ...steps.map((s, i) => `${i + 1}. ${s}`),
    "",
    `Get Started: ${origin}/Dashboard`,
  ].join("\n");
  return { subject: WELCOME_SUBJECT, html, text };
}
