-- Native POS schema for Supabase SQL Editor. Safe to re-run.
-- Applies webhook POS tables (if missing) then every 20260828 native-POS migration in order.
-- Do not run 20260828120000_drop_affiliate_program.sql here.
-- Generated by scripts/generate-apply-native-pos.mjs — edit the migrations, then regenerate.

-- ═══════════════════════════════════════════════════════════════════════════
-- scripts/apply-pos-integrations.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Apply POS integration tables (run once in Supabase → SQL Editor).
-- Combines:
--   supabase/migrations/20260709180000_pos_integrations.sql
--   supabase/migrations/20260709183000_pos_oauth_states.sql
-- Safe to re-run (IF NOT EXISTS / DROP POLICY IF EXISTS).

-- Requires public.is_org_member(uuid) from migration 20260624120000_fix_org_membership_rls_recursion.sql

-- ── pos_connections + pos_sales_events ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pos_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('generic', 'yoco', 'square')),
  label text NOT NULL DEFAULT 'POS Connection',
  webhook_token text NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(24), 'hex'),
  webhook_secret text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_event_at timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pos_connections_org_id ON public.pos_connections(org_id);
CREATE INDEX IF NOT EXISTS idx_pos_connections_webhook_token ON public.pos_connections(webhook_token);

CREATE TABLE IF NOT EXISTS public.pos_sales_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  connection_id uuid NOT NULL REFERENCES public.pos_connections(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  provider text NOT NULL,
  status text NOT NULL DEFAULT 'completed',
  total_amount numeric(14, 2) NOT NULL,
  currency text NOT NULL DEFAULT 'ZAR',
  payment_method text,
  occurred_at timestamptz NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  inventory_result jsonb,
  inventory_applied boolean NOT NULL DEFAULT false,
  raw_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pos_sales_events_connection_external_unique UNIQUE (connection_id, external_id)
);

CREATE INDEX IF NOT EXISTS idx_pos_sales_events_org_occurred
  ON public.pos_sales_events(org_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_pos_sales_events_connection_id
  ON public.pos_sales_events(connection_id);

ALTER TABLE public.pos_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_sales_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pos_connections_org_select" ON public.pos_connections;
CREATE POLICY "pos_connections_org_select"
  ON public.pos_connections
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

DROP POLICY IF EXISTS "pos_connections_org_manage" ON public.pos_connections;
CREATE POLICY "pos_connections_org_manage"
  ON public.pos_connections
  FOR ALL
  TO authenticated
  USING (public.is_company_admin_for_org(org_id))
  WITH CHECK (public.is_company_admin_for_org(org_id));

DROP POLICY IF EXISTS "pos_sales_events_org_select" ON public.pos_sales_events;
CREATE POLICY "pos_sales_events_org_select"
  ON public.pos_sales_events
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

GRANT EXECUTE ON FUNCTION public.adjust_inventory_stock(uuid, uuid, integer, text, text, uuid) TO service_role;

GRANT ALL ON TABLE public.pos_connections TO service_role;
GRANT ALL ON TABLE public.pos_sales_events TO service_role;

-- ── pos_oauth_states (Square OAuth CSRF) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pos_oauth_states (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('square', 'yoco')),
  state_token text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pos_oauth_states_expires_at ON public.pos_oauth_states(expires_at);

ALTER TABLE public.pos_oauth_states ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.pos_oauth_states TO service_role;

-- Notify PostgREST to reload schema cache (Supabase API)
NOTIFY pgrst, 'reload schema';

-- If DELETE /api/pos/connections/:id fails with FK errors, also run:
-- supabase/migrations/20260709190000_pos_sales_events_cascade_delete.sql
-- supabase/migrations/20260709191000_pos_delete_connection_rpc.sql

CREATE OR REPLACE FUNCTION public.delete_pos_connection(
  p_org_id uuid,
  p_connection_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted boolean := false;
BEGIN
  IF p_org_id IS NULL OR p_connection_id IS NULL THEN
    RETURN false;
  END IF;

  DELETE FROM public.pos_sales_events
  WHERE connection_id = p_connection_id;

  DELETE FROM public.pos_connections
  WHERE id = p_connection_id
    AND org_id = p_org_id
  RETURNING true INTO deleted;

  RETURN COALESCE(deleted, false);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_pos_connection(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_pos_connection(uuid, uuid) TO service_role;

NOTIFY pgrst, 'reload schema';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828160000_native_pos_checkout.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Native Paidly POS: same pos_sales_events + inventory RPC as Yoco/Square ingress.
-- provider 'paidly' is an in-app till, not a webhook connection.
-- Requires pos_connections + pos_sales_events (scripts/apply-pos-integrations.sql).

DO $$
BEGIN
  IF to_regclass('public.pos_connections') IS NULL OR to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE EXCEPTION 'pos_connections/pos_sales_events missing. Run scripts/apply-pos-integrations.sql first, then re-run this file.';
  END IF;
END $$;

ALTER TABLE public.pos_connections
  DROP CONSTRAINT IF EXISTS pos_connections_provider_check;

ALTER TABLE public.pos_connections
  ADD CONSTRAINT pos_connections_provider_check
  CHECK (provider IN ('generic', 'yoco', 'square', 'paidly'));

-- Native till sales are not tied to a webhook connection.
ALTER TABLE public.pos_sales_events
  ALTER COLUMN connection_id DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_connections_one_paidly_per_org
  ON public.pos_connections (org_id)
  WHERE provider = 'paidly';

ALTER TABLE public.pos_sales_events
  ADD COLUMN IF NOT EXISTS receipt_number text,
  ADD COLUMN IF NOT EXISTS client_id uuid,
  ADD COLUMN IF NOT EXISTS company_id uuid,
  ADD COLUMN IF NOT EXISTS cashier_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sale_kind text NOT NULL DEFAULT 'sale',
  ADD COLUMN IF NOT EXISTS parent_event_id uuid REFERENCES public.pos_sales_events(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS amount_tendered numeric(14, 2),
  ADD COLUMN IF NOT EXISTS change_due numeric(14, 2);

DO $$
BEGIN
  IF to_regclass('public.clients') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_client_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.pos_sales_events
        ADD CONSTRAINT pos_sales_events_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE SET NULL
    $c$;
  END IF;
  IF to_regclass('public.companies') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_company_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.pos_sales_events
        ADD CONSTRAINT pos_sales_events_company_id_fkey
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
    $c$;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pos_sales_events_sale_kind_check'
      AND conrelid = 'public.pos_sales_events'::regclass
  ) THEN
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_sale_kind_check
      CHECK (sale_kind IN ('sale', 'return'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_sales_events_org_receipt
  ON public.pos_sales_events (org_id, receipt_number)
  WHERE receipt_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pos_sales_events_parent
  ON public.pos_sales_events (parent_event_id)
  WHERE parent_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pos_sales_events_cashier
  ON public.pos_sales_events (org_id, cashier_id, occurred_at DESC);

COMMENT ON COLUMN public.pos_sales_events.sale_kind IS
  'sale = retail checkout; return = restock against parent_event_id.';
COMMENT ON COLUMN public.pos_connections.provider IS
  'generic | yoco | square (webhook adapters) | paidly (native till).';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828180000_payment_intents.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Canonical Payment Intent layer (Document Engine / POS ↔ customer payment rails).
-- PayFast is SaaS subscription billing only — it must not appear as a customer-payment provider.
-- POS settlement remains pos_sales_events (not invoice payments, not payment_history).
-- Safe in SQL Editor: uses gen_random_uuid(); FKs to optional tables are added only when those relations exist.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.payment_intents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  source_kind text NOT NULL CHECK (source_kind IN ('document', 'pos')),
  document_id uuid,
  document_type text,
  pos_sale_event_id uuid,
  provider text NOT NULL,
  amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
  currency text NOT NULL DEFAULT 'ZAR',
  status text NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'requires_action', 'processing', 'paid', 'failed', 'cancelled', 'expired', 'refunded')
  ),
  external_id text,
  idempotency_key text,
  client_id uuid,
  company_id uuid,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payment_intents_pos_provider_check CHECK (
    (source_kind = 'pos' AND provider IN ('cash', 'ozow'))
    OR (source_kind = 'document' AND provider IN ('ozow'))
  ),
  CONSTRAINT payment_intents_document_ref_check CHECK (
    source_kind <> 'document' OR document_id IS NOT NULL
  )
);

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.payment_intents DROP CONSTRAINT IF EXISTS payment_intents_pos_sale_event_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.payment_intents
        ADD CONSTRAINT payment_intents_pos_sale_event_id_fkey
        FOREIGN KEY (pos_sale_event_id) REFERENCES public.pos_sales_events(id) ON DELETE SET NULL
    $c$;
  ELSE
    RAISE NOTICE 'pos_sales_events missing — skip payment_intents.pos_sale_event_id FK (run scripts/apply-pos-integrations.sql)';
  END IF;

  IF to_regclass('public.clients') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.payment_intents DROP CONSTRAINT IF EXISTS payment_intents_client_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.payment_intents
        ADD CONSTRAINT payment_intents_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE SET NULL
    $c$;
  END IF;

  IF to_regclass('public.companies') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.payment_intents DROP CONSTRAINT IF EXISTS payment_intents_company_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.payment_intents
        ADD CONSTRAINT payment_intents_company_id_fkey
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
    $c$;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_intents_org_idempotency
  ON public.payment_intents (org_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_intents_org_created
  ON public.payment_intents (org_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_payment_intents_pos_sale
  ON public.payment_intents (pos_sale_event_id)
  WHERE pos_sale_event_id IS NOT NULL;

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE NOTICE 'pos_sales_events missing — skip payment_intent_id column';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.pos_sales_events ADD COLUMN IF NOT EXISTS payment_intent_id uuid';
  EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_payment_intent_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_payment_intent_id_fkey
      FOREIGN KEY (payment_intent_id) REFERENCES public.payment_intents(id) ON DELETE SET NULL
  $c$;
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_pos_sales_events_payment_intent ON public.pos_sales_events (payment_intent_id) WHERE payment_intent_id IS NOT NULL';
  EXECUTE $c$
    COMMENT ON COLUMN public.pos_sales_events.payment_intent_id IS
      'Intent that verified this till sale. Cash and Ozow go through payment_intents first.'
  $c$;
END $$;

ALTER TABLE public.payment_intents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payment_intents_org_select" ON public.payment_intents;
CREATE POLICY "payment_intents_org_select"
  ON public.payment_intents
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

GRANT ALL ON TABLE public.payment_intents TO service_role;
GRANT SELECT ON TABLE public.payment_intents TO authenticated;

COMMENT ON TABLE public.payment_intents IS
  'Customer payment handoff. source_kind=pos settles to pos_sales_events; source_kind=document settles to invoice payments. PayFast is not a provider here.';
COMMENT ON COLUMN public.payment_intents.provider IS
  'Customer rail: cash (till-verified) or ozow (online). Never payfast.';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828190000_payment_intents_card_terminal.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Card is a physical-terminal rail, not Ozow and not click-to-paid.
-- Native till has no card-present SDK; intents may be created but must not settle as paid
-- until a real terminal/provider confirmation exists.

DO $$
BEGIN
  IF to_regclass('public.payment_intents') IS NULL THEN
    RAISE EXCEPTION 'payment_intents missing. Apply 20260828180000_payment_intents.sql first.';
  END IF;
END $$;

ALTER TABLE public.payment_intents
  DROP CONSTRAINT IF EXISTS payment_intents_pos_provider_check;

ALTER TABLE public.payment_intents
  ADD CONSTRAINT payment_intents_pos_provider_check CHECK (
    (source_kind = 'pos' AND provider IN ('cash', 'ozow', 'card_terminal'))
    OR (source_kind = 'document' AND provider IN ('ozow'))
  );

COMMENT ON COLUMN public.payment_intents.provider IS
  'Customer rail: cash (till-verified), ozow (digital/EFT), card_terminal (hardware — not faked). Never payfast.';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828200000_pos_sale_invoice.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Optional tax-invoice copy of a settled POS sale.
-- POS checkout does not create invoices. Convert is opt-in (Customer requests invoice).
-- Money stays on pos_sales_events. Stock already moved with source=pos; skip invoice inventory triggers.

DO $$
BEGIN
  IF to_regclass('public.invoices') IS NULL THEN
    RAISE EXCEPTION 'invoices missing — cannot add pos_sale_event_id';
  END IF;
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE EXCEPTION 'pos_sales_events missing. Run scripts/apply-pos-integrations.sql first.';
  END IF;
END $$;

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS pos_sale_event_id uuid;

DO $$
BEGIN
  EXECUTE 'ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_pos_sale_event_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.invoices
      ADD CONSTRAINT invoices_pos_sale_event_id_fkey
      FOREIGN KEY (pos_sale_event_id) REFERENCES public.pos_sales_events(id) ON DELETE SET NULL
  $c$;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_pos_sale_event_id
  ON public.invoices (pos_sale_event_id)
  WHERE pos_sale_event_id IS NOT NULL;

ALTER TABLE public.pos_sales_events
  ADD COLUMN IF NOT EXISTS invoice_id uuid;

DO $$
BEGIN
  EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_invoice_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_invoice_id_fkey
      FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL
  $c$;
END $$;

CREATE INDEX IF NOT EXISTS idx_pos_sales_events_invoice_id
  ON public.pos_sales_events (invoice_id)
  WHERE invoice_id IS NOT NULL;

COMMENT ON COLUMN public.invoices.pos_sale_event_id IS
  'Optional tax-invoice copy of a settled POS sale. Not a new receivable. Money stays on pos_sales_events; do not insert invoice payments.';

COMMENT ON COLUMN public.pos_sales_events.invoice_id IS
  'Optional invoices.id when the customer requested a tax invoice for this till sale.';

CREATE OR REPLACE FUNCTION public.handle_invoice_paid()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  r RECORD;
  v_current_stock integer;
  v_qty integer;
  v_delta integer;
BEGIN
  -- POS already decremented stock via adjust_inventory_stock (source=pos).
  IF NEW.pos_sale_event_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.status = 'paid' AND (OLD.status IS DISTINCT FROM 'paid') THEN

    FOR r IN
      SELECT ii.service_id AS product_id, ii.quantity AS qty
      FROM public.invoice_items ii
      JOIN public.services s ON s.id = ii.service_id
      WHERE ii.invoice_id = NEW.id
        AND COALESCE(s.item_type, 'service') = 'product'
    LOOP
      SELECT stock_quantity INTO v_current_stock
      FROM public.services
      WHERE id = r.product_id
        AND org_id = NEW.org_id
      FOR UPDATE;

      v_qty := GREATEST(COALESCE(r.qty, 0)::integer, 0);
      v_delta := -LEAST(v_qty, COALESCE(v_current_stock, 0));

      IF v_delta <> 0 THEN
        PERFORM public.apply_inventory_movement(
          r.product_id, NEW.org_id, v_delta, 'out', 'invoice', NEW.id
        );
      END IF;
    END LOOP;

  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_invoice_reversal()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  r RECORD;
  v_qty integer;
BEGIN
  IF NEW.pos_sale_event_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF OLD.status = 'paid' AND NEW.status <> 'paid' THEN

    FOR r IN
      SELECT ii.service_id AS product_id, ii.quantity AS qty
      FROM public.invoice_items ii
      JOIN public.services s ON s.id = ii.service_id
      WHERE ii.invoice_id = NEW.id
        AND COALESCE(s.item_type, 'service') = 'product'
    LOOP
      v_qty := GREATEST(COALESCE(r.qty, 0)::integer, 0);
      IF v_qty <> 0 THEN
        PERFORM public.apply_inventory_movement(
          r.product_id, NEW.org_id, v_qty, 'in', 'invoice_reversal', NEW.id
        );
      END IF;
    END LOOP;

  END IF;

  RETURN NEW;
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828210000_pos_registers.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Native POS register: a till identity on an org brand (public.companies).
-- Paidly has no locations table — do not invent a multi-site model here.
-- Sale SoR stays pos_sales_events. This is not a parallel POS ledger, session, or payments table.

CREATE TABLE IF NOT EXISTS public.pos_registers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  company_id uuid,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  assigned_staff_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  opening_balance numeric(14, 2) NOT NULL DEFAULT 0 CHECK (opening_balance >= 0),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pos_registers_name_not_blank CHECK (char_length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_registers_org_name
  ON public.pos_registers (org_id, lower(btrim(name)));

CREATE INDEX IF NOT EXISTS idx_pos_registers_org_status
  ON public.pos_registers (org_id, status);

CREATE INDEX IF NOT EXISTS idx_pos_registers_company
  ON public.pos_registers (company_id)
  WHERE company_id IS NOT NULL;

DO $$
BEGIN
  IF to_regclass('public.companies') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.pos_registers DROP CONSTRAINT IF EXISTS pos_registers_company_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.pos_registers
        ADD CONSTRAINT pos_registers_company_id_fkey
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
    $c$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE NOTICE 'pos_sales_events missing — skip register_id';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.pos_sales_events ADD COLUMN IF NOT EXISTS register_id uuid';
  EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_register_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_register_id_fkey
      FOREIGN KEY (register_id) REFERENCES public.pos_registers(id) ON DELETE SET NULL
  $c$;
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_pos_sales_events_register ON public.pos_sales_events (register_id) WHERE register_id IS NOT NULL';
END $$;

ALTER TABLE public.pos_registers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pos_registers_org_select" ON public.pos_registers;
CREATE POLICY "pos_registers_org_select"
  ON public.pos_registers
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

DROP POLICY IF EXISTS "pos_registers_org_manage" ON public.pos_registers;
CREATE POLICY "pos_registers_org_manage"
  ON public.pos_registers
  FOR ALL
  TO authenticated
  USING (public.is_company_admin_for_org(org_id))
  WITH CHECK (public.is_company_admin_for_org(org_id));

GRANT ALL ON TABLE public.pos_registers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pos_registers TO authenticated;

COMMENT ON TABLE public.pos_registers IS
  'Physical till identity. Belongs to org + optional brand (companies). No locations table exists — do not add a site model here. Opening balance is the cash float, not a sale.';

COMMENT ON COLUMN public.pos_registers.company_id IS
  'Brand (public.companies.id). Same trading identity as invoices.company_id.';

COMMENT ON COLUMN public.pos_registers.assigned_staff_id IS
  'Operational assignment. Checkout cashier_id is still the signed-in user.';

COMMENT ON COLUMN public.pos_registers.opening_balance IS
  'Expected cash float in the drawer. Not POS sale money, not invoice payments.';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'pos_sales_events' AND column_name = 'register_id'
  ) THEN
    EXECUTE $c$
      COMMENT ON COLUMN public.pos_sales_events.register_id IS
        'Till that recorded this sale. Optional so Yoco/Square ingress still works without a native register.'
    $c$;
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828220000_pos_register_sessions.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- POS register shift sessions (cash drawer), not Auth sessions.
-- Sale SoR stays pos_sales_events. Closed sessions are immutable.
-- If pos_registers is missing (SQL Editor applied this file first), create it here.

CREATE TABLE IF NOT EXISTS public.pos_registers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  company_id uuid,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  assigned_staff_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  opening_balance numeric(14, 2) NOT NULL DEFAULT 0 CHECK (opening_balance >= 0),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pos_registers_name_not_blank CHECK (char_length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_registers_org_name
  ON public.pos_registers (org_id, lower(btrim(name)));

CREATE INDEX IF NOT EXISTS idx_pos_registers_org_status
  ON public.pos_registers (org_id, status);

CREATE INDEX IF NOT EXISTS idx_pos_registers_company
  ON public.pos_registers (company_id)
  WHERE company_id IS NOT NULL;

DO $$
BEGIN
  IF to_regclass('public.companies') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.pos_registers DROP CONSTRAINT IF EXISTS pos_registers_company_id_fkey';
    EXECUTE $c$
      ALTER TABLE public.pos_registers
        ADD CONSTRAINT pos_registers_company_id_fkey
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
    $c$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.pos_register_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  register_id uuid NOT NULL REFERENCES public.pos_registers(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  opening_balance numeric(14, 2) NOT NULL DEFAULT 0 CHECK (opening_balance >= 0),
  cash_sales numeric(14, 2) NOT NULL DEFAULT 0 CHECK (cash_sales >= 0),
  cash_refunds numeric(14, 2) NOT NULL DEFAULT 0 CHECK (cash_refunds >= 0),
  expected_cash numeric(14, 2) NOT NULL DEFAULT 0,
  closing_cash numeric(14, 2) CHECK (closing_cash IS NULL OR closing_cash >= 0),
  variance numeric(14, 2),
  opened_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  closed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  opened_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pos_register_sessions_closed_complete CHECK (
    (status = 'open' AND closed_at IS NULL AND closing_cash IS NULL AND variance IS NULL)
    OR
    (status = 'closed' AND closed_at IS NOT NULL AND closing_cash IS NOT NULL AND variance IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_register_sessions_one_open
  ON public.pos_register_sessions (register_id)
  WHERE status = 'open';

CREATE INDEX IF NOT EXISTS idx_pos_register_sessions_org_opened
  ON public.pos_register_sessions (org_id, opened_at DESC);

CREATE INDEX IF NOT EXISTS idx_pos_register_sessions_register
  ON public.pos_register_sessions (register_id, opened_at DESC);

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE NOTICE 'pos_sales_events missing — skip session_id';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.pos_sales_events ADD COLUMN IF NOT EXISTS session_id uuid';
  EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_session_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_session_id_fkey
      FOREIGN KEY (session_id) REFERENCES public.pos_register_sessions(id) ON DELETE SET NULL
  $c$;
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_pos_sales_events_session ON public.pos_sales_events (session_id) WHERE session_id IS NOT NULL';
END $$;

ALTER TABLE public.pos_register_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pos_register_sessions_org_select" ON public.pos_register_sessions;
CREATE POLICY "pos_register_sessions_org_select"
  ON public.pos_register_sessions
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

DROP POLICY IF EXISTS "pos_register_sessions_org_write" ON public.pos_register_sessions;
CREATE POLICY "pos_register_sessions_org_write"
  ON public.pos_register_sessions
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_org_member(org_id));

DROP POLICY IF EXISTS "pos_register_sessions_org_update" ON public.pos_register_sessions;
CREATE POLICY "pos_register_sessions_org_update"
  ON public.pos_register_sessions
  FOR UPDATE
  TO authenticated
  USING (public.is_org_member(org_id) AND status = 'open')
  WITH CHECK (public.is_org_member(org_id));

CREATE OR REPLACE FUNCTION public.pos_register_session_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status = 'closed' THEN
      RAISE EXCEPTION 'Completed POS sessions cannot be edited';
    END IF;
    RETURN OLD;
  END IF;

  IF OLD.status = 'closed' THEN
    RAISE EXCEPTION 'Completed POS sessions cannot be edited';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_pos_register_session_immutable ON public.pos_register_sessions;
CREATE TRIGGER tr_pos_register_session_immutable
BEFORE UPDATE OR DELETE ON public.pos_register_sessions
FOR EACH ROW
EXECUTE FUNCTION public.pos_register_session_immutable();

GRANT ALL ON TABLE public.pos_register_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.pos_register_sessions TO authenticated;

COMMENT ON TABLE public.pos_register_sessions IS
  'Cash-drawer shift on a POS register. Not Auth. Closed rows are immutable. Cash totals snapshot at close from pos_sales_events.';

COMMENT ON COLUMN public.pos_register_sessions.opening_balance IS
  'Cash counted into the drawer when the shift opens. Prefills from pos_registers.opening_balance.';

COMMENT ON COLUMN public.pos_register_sessions.expected_cash IS
  'opening_balance + cash_sales - cash_refunds. Snapshotted at close.';

COMMENT ON COLUMN public.pos_register_sessions.variance IS
  'closing_cash - expected_cash. Set only when the session is closed.';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'pos_sales_events' AND column_name = 'session_id'
  ) THEN
    EXECUTE $c$
      COMMENT ON COLUMN public.pos_sales_events.session_id IS
        'Open register shift that recorded this native till sale. External Yoco/Square ingress may omit it.'
    $c$;
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828230000_pos_return_audit.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Append-only POS returns. The original sale is never deleted to reverse money.
-- Refund state is derived from child sale_kind=return rows and snapshotted on the sale.
-- Card/digital provider refunds (Ozow / card_terminal) are not V1: stamp pending_provider
-- and keep payment_intents.refund_of_intent_id for a later refund intent.

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE EXCEPTION 'pos_sales_events missing. Run scripts/apply-pos-integrations.sql first.';
  END IF;
END $$;

ALTER TABLE public.pos_sales_events
  ADD COLUMN IF NOT EXISTS refund_status text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS refunded_amount numeric(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS refund_rail text,
  ADD COLUMN IF NOT EXISTS original_payment_intent_id uuid;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pos_sales_events_refund_status_check'
      AND conrelid = 'public.pos_sales_events'::regclass
  ) THEN
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_refund_status_check
      CHECK (refund_status IN ('none', 'partial', 'full'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pos_sales_events_refund_rail_check'
      AND conrelid = 'public.pos_sales_events'::regclass
  ) THEN
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_refund_rail_check
      CHECK (refund_rail IS NULL OR refund_rail IN ('till_cash', 'pending_provider', 'provider'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pos_sales_events_refunded_amount_check'
      AND conrelid = 'public.pos_sales_events'::regclass
  ) THEN
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_refunded_amount_check
      CHECK (refunded_amount >= 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pos_sales_events_refund_status
  ON public.pos_sales_events (org_id, refund_status)
  WHERE sale_kind = 'sale' AND refund_status <> 'none';

UPDATE public.pos_sales_events
SET refund_rail = CASE
  WHEN lower(coalesce(payment_method, 'cash')) = 'cash' THEN 'till_cash'
  ELSE 'pending_provider'
END
WHERE sale_kind = 'return'
  AND refund_rail IS NULL;

DO $$
BEGIN
  IF to_regclass('public.payment_intents') IS NULL THEN
    RAISE NOTICE 'payment_intents missing — skip refund_of_intent_id (apply 20260828180000_payment_intents.sql)';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.payment_intents ADD COLUMN IF NOT EXISTS refund_of_intent_id uuid';
  EXECUTE 'ALTER TABLE public.payment_intents DROP CONSTRAINT IF EXISTS payment_intents_refund_of_intent_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.payment_intents
      ADD CONSTRAINT payment_intents_refund_of_intent_id_fkey
      FOREIGN KEY (refund_of_intent_id) REFERENCES public.payment_intents(id) ON DELETE SET NULL
  $c$;
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_payment_intents_refund_of ON public.payment_intents (refund_of_intent_id) WHERE refund_of_intent_id IS NOT NULL';
  EXECUTE $c$
    COMMENT ON COLUMN public.payment_intents.refund_of_intent_id IS
      'Future provider refund intent pointing at the original paid intent. Unused in V1.'
  $c$;
  EXECUTE 'ALTER TABLE public.pos_sales_events DROP CONSTRAINT IF EXISTS pos_sales_events_original_payment_intent_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_sales_events
      ADD CONSTRAINT pos_sales_events_original_payment_intent_id_fkey
      FOREIGN KEY (original_payment_intent_id) REFERENCES public.payment_intents(id) ON DELETE SET NULL
  $c$;
END $$;

-- Financial identity is immutable. Operational fields (inventory flags, invoice
-- link, refund snapshot, client attach, refund_rail completion) may still change.
-- DELETE is not blocked here: pos_connections.connection_id ON DELETE CASCADE
-- must still remove events when a connection is deleted. Returns must INSERT a
-- child row instead of DELETE/UPDATE of totals.

CREATE OR REPLACE FUNCTION public.pos_sales_event_financial_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.total_amount IS DISTINCT FROM OLD.total_amount
     OR NEW.items IS DISTINCT FROM OLD.items
     OR NEW.sale_kind IS DISTINCT FROM OLD.sale_kind
     OR NEW.parent_event_id IS DISTINCT FROM OLD.parent_event_id
     OR NEW.payment_method IS DISTINCT FROM OLD.payment_method
     OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
     OR NEW.receipt_number IS DISTINCT FROM OLD.receipt_number
     OR NEW.amount_tendered IS DISTINCT FROM OLD.amount_tendered
     OR NEW.change_due IS DISTINCT FROM OLD.change_due
     OR NEW.currency IS DISTINCT FROM OLD.currency
     OR NEW.external_id IS DISTINCT FROM OLD.external_id
     OR NEW.provider IS DISTINCT FROM OLD.provider
     OR NEW.connection_id IS DISTINCT FROM OLD.connection_id
     OR NEW.org_id IS DISTINCT FROM OLD.org_id
     OR NEW.cashier_id IS DISTINCT FROM OLD.cashier_id
     OR NEW.register_id IS DISTINCT FROM OLD.register_id
     OR NEW.session_id IS DISTINCT FROM OLD.session_id
     OR NEW.company_id IS DISTINCT FROM OLD.company_id
     OR NEW.original_payment_intent_id IS DISTINCT FROM OLD.original_payment_intent_id
  THEN
    RAISE EXCEPTION 'POS sales cannot change financial fields; record a return instead';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_pos_sales_event_financial_immutable ON public.pos_sales_events;
CREATE TRIGGER tr_pos_sales_event_financial_immutable
BEFORE UPDATE ON public.pos_sales_events
FOR EACH ROW
EXECUTE FUNCTION public.pos_sales_event_financial_immutable();

COMMENT ON COLUMN public.pos_sales_events.refund_status IS
  'Snapshot on the original sale: none | partial | full. Derived from child return events. Original totals are never rewritten.';

COMMENT ON COLUMN public.pos_sales_events.refunded_amount IS
  'Sum of abs(child return total_amount). Original total_amount stays the sale total.';

COMMENT ON COLUMN public.pos_sales_events.refund_rail IS
  'On return rows: till_cash (drawer), pending_provider (V1 card/digital restock), provider (future Ozow/terminal refund).';

COMMENT ON COLUMN public.pos_sales_events.original_payment_intent_id IS
  'Original sale payment_intents.id copied onto the return. V1 does not mark that intent refunded.';

COMMENT ON COLUMN public.pos_sales_events.sale_kind IS
  'sale = retail checkout; return = append-only restock/refund against parent_event_id. Never delete the original sale to reverse it.';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828240000_pos_multibrand_catalog.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Optional brand ownership on the existing catalog (public.services).
-- Null company_id = org-shared (visible on every till). Set company_id = private
-- to that brand; Company A's POS must not sell Company B's private products.
-- Do not add a second products table. Same companies.id as invoices.company_id
-- and pos_registers.company_id.

DO $$
BEGIN
  IF to_regclass('public.services') IS NULL THEN
    RAISE EXCEPTION 'services missing — cannot add catalog brand ownership';
  END IF;
END $$;

ALTER TABLE public.services
  ADD COLUMN IF NOT EXISTS company_id uuid;

DO $$
BEGIN
  IF to_regclass('public.companies') IS NULL THEN
    RAISE NOTICE 'companies missing — skip services.company_id FK';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.services DROP CONSTRAINT IF EXISTS services_company_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.services
      ADD CONSTRAINT services_company_id_fkey
      FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
  $c$;
END $$;

CREATE INDEX IF NOT EXISTS idx_services_org_company
  ON public.services (org_id, company_id)
  WHERE company_id IS NOT NULL;

COMMENT ON COLUMN public.services.company_id IS
  'Brand (public.companies.id). Null = org-shared catalog. Set = private to that brand; POS tills on other brands cannot sell it.';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828250000_pos_audit_trail.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Append-only POS audit trail (document_events / subscription_events pattern).
-- Sale SoR stays pos_sales_events. Money fields stay immutable (existing trigger).
-- Deleting a POS connection must not erase completed sales.
-- payment_intents (20260828180000) is preferred. If it is missing, create the audit
-- table without that FK so this file still applies.

ALTER TABLE public.pos_sales_events
  ALTER COLUMN connection_id DROP NOT NULL;

ALTER TABLE public.pos_sales_events
  DROP CONSTRAINT IF EXISTS pos_sales_events_connection_id_fkey;

ALTER TABLE public.pos_sales_events
  ADD CONSTRAINT pos_sales_events_connection_id_fkey
  FOREIGN KEY (connection_id) REFERENCES public.pos_connections(id) ON DELETE SET NULL;

-- connection_id is hardware linkage, not money identity. Disconnect SET NULLs it.
CREATE OR REPLACE FUNCTION public.pos_sales_event_financial_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.total_amount IS DISTINCT FROM OLD.total_amount
     OR NEW.items IS DISTINCT FROM OLD.items
     OR NEW.sale_kind IS DISTINCT FROM OLD.sale_kind
     OR NEW.parent_event_id IS DISTINCT FROM OLD.parent_event_id
     OR NEW.payment_method IS DISTINCT FROM OLD.payment_method
     OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
     OR NEW.receipt_number IS DISTINCT FROM OLD.receipt_number
     OR NEW.amount_tendered IS DISTINCT FROM OLD.amount_tendered
     OR NEW.change_due IS DISTINCT FROM OLD.change_due
     OR NEW.currency IS DISTINCT FROM OLD.currency
     OR NEW.external_id IS DISTINCT FROM OLD.external_id
     OR NEW.provider IS DISTINCT FROM OLD.provider
     OR NEW.org_id IS DISTINCT FROM OLD.org_id
     OR NEW.cashier_id IS DISTINCT FROM OLD.cashier_id
     OR NEW.register_id IS DISTINCT FROM OLD.register_id
     OR NEW.session_id IS DISTINCT FROM OLD.session_id
     OR NEW.company_id IS DISTINCT FROM OLD.company_id
     OR NEW.original_payment_intent_id IS DISTINCT FROM OLD.original_payment_intent_id
  THEN
    RAISE EXCEPTION 'POS sales cannot change financial fields; record a return instead';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_pos_connection(
  p_org_id uuid,
  p_connection_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted boolean := false;
BEGIN
  IF p_org_id IS NULL OR p_connection_id IS NULL THEN
    RETURN false;
  END IF;

  UPDATE public.pos_sales_events
  SET connection_id = NULL
  WHERE connection_id = p_connection_id
    AND org_id = p_org_id;

  DELETE FROM public.pos_connections
  WHERE id = p_connection_id
    AND org_id = p_org_id
  RETURNING true INTO deleted;

  RETURN COALESCE(deleted, false);
END;
$$;

CREATE TABLE IF NOT EXISTS public.pos_audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  sale_event_id uuid REFERENCES public.pos_sales_events(id) ON DELETE CASCADE,
  payment_intent_id uuid,
  event_type text NOT NULL CHECK (
    event_type IN (
      'sale_created',
      'payment',
      'completion',
      'refund',
      'cancellation',
      'inventory_movement'
    )
  ),
  actor_type text NOT NULL DEFAULT 'user' CHECK (actor_type IN ('user', 'system', 'webhook')),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF to_regclass('public.payment_intents') IS NULL THEN
    RAISE NOTICE 'payment_intents missing — apply 20260828180000_payment_intents.sql then re-run this file for the FK';
    RETURN;
  END IF;
  EXECUTE 'ALTER TABLE public.pos_audit_events DROP CONSTRAINT IF EXISTS pos_audit_events_payment_intent_id_fkey';
  EXECUTE $c$
    ALTER TABLE public.pos_audit_events
      ADD CONSTRAINT pos_audit_events_payment_intent_id_fkey
      FOREIGN KEY (payment_intent_id) REFERENCES public.payment_intents(id) ON DELETE CASCADE
  $c$;
END $$;

CREATE INDEX IF NOT EXISTS idx_pos_audit_events_org_occurred
  ON public.pos_audit_events (org_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_pos_audit_events_sale
  ON public.pos_audit_events (sale_event_id, occurred_at ASC)
  WHERE sale_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pos_audit_events_intent
  ON public.pos_audit_events (payment_intent_id, occurred_at ASC)
  WHERE payment_intent_id IS NOT NULL;

ALTER TABLE public.pos_audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pos_audit_events_org_select" ON public.pos_audit_events;
CREATE POLICY "pos_audit_events_org_select"
  ON public.pos_audit_events
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

GRANT ALL ON TABLE public.pos_audit_events TO service_role;
GRANT SELECT ON TABLE public.pos_audit_events TO authenticated;

CREATE OR REPLACE FUNCTION public.pos_audit_event_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION 'POS audit events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS tr_pos_audit_event_no_update ON public.pos_audit_events;
CREATE TRIGGER tr_pos_audit_event_no_update
BEFORE UPDATE ON public.pos_audit_events
FOR EACH ROW
EXECUTE FUNCTION public.pos_audit_event_append_only();

COMMENT ON TABLE public.pos_audit_events IS
  'Append-only till lifecycle: sale_created, payment, completion, refund, cancellation, inventory_movement. Not a second sales ledger.';

COMMENT ON COLUMN public.pos_sales_events.connection_id IS
  'POS connection that ingested this sale. SET NULL if the connection is removed so completed sales stay auditable.';

REVOKE ALL ON FUNCTION public.delete_pos_connection(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_pos_connection(uuid, uuid) TO service_role;

NOTIFY pgrst, 'reload schema';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828260000_pos_rls_tenant_integrity.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- POS tenancy: org-scoped RLS, brand/staff/register integrity, client cannot write the till ledger.
-- Money writes stay on the API (service_role). SELECT stays org-member so Cash Flow / Reports can read.
-- Requires 20260828180000_payment_intents.sql and 20260828250000_pos_audit_trail.sql.
-- Tables that are not present yet are skipped (REVOKE / policy / trigger) so this file still applies.

-- ── Permission helper (mirrors server/src/companyRouteAccess.js POS grants) ────
CREATE OR REPLACE FUNCTION public.org_has_pos_permission(target_org_id uuid, permission text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF target_org_id IS NULL OR permission IS NULL OR btrim(permission) = '' THEN
    RETURN false;
  END IF;

  IF public.is_company_admin_for_org(target_org_id) THEN
    RETURN permission IN (
      'pos_access',
      'pos_sell',
      'pos_discount',
      'pos_refund',
      'pos_close_register',
      'pos_view_reports'
    );
  END IF;

  IF public.is_company_manager_for_org(target_org_id) THEN
    RETURN permission IN (
      'pos_access',
      'pos_sell',
      'pos_discount',
      'pos_refund',
      'pos_close_register',
      'pos_view_reports'
    );
  END IF;

  IF public.is_org_member(target_org_id) THEN
    RETURN permission IN ('pos_access', 'pos_sell');
  END IF;

  RETURN false;
END;
$$;

COMMENT ON FUNCTION public.org_has_pos_permission(uuid, text) IS
  'Org RBAC for POS. Admin/manager/owner: all till grants. Employee member: pos_access + pos_sell. No second POS role table.';

GRANT EXECUTE ON FUNCTION public.org_has_pos_permission(uuid, text) TO authenticated;

-- ── Client cannot write till money or shifts (API uses service_role) ───────────
DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NULL THEN
    RAISE EXCEPTION 'pos_sales_events missing. Run scripts/apply-pos-integrations.sql first.';
  END IF;
END $$;

GRANT SELECT ON TABLE public.pos_sales_events TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.pos_sales_events FROM authenticated, anon;
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'pos_audit_events',
    'payment_intents',
    'pos_register_sessions',
    'pos_registers',
    'pos_connections'
  ]
  LOOP
    IF to_regclass('public.' || t) IS NULL THEN
      RAISE NOTICE '% missing — skip write REVOKE; apply the matching 20260828 POS migration then re-run this file', t;
    ELSE
      EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON TABLE public.%I FROM authenticated, anon', t);
    END IF;
  END LOOP;
END $$;

DO $$
BEGIN
  IF to_regclass('public.pos_register_sessions') IS NULL THEN
    RAISE NOTICE 'pos_register_sessions missing — apply 20260828220000_pos_register_sessions.sql';
  ELSE
    EXECUTE 'GRANT SELECT ON TABLE public.pos_register_sessions TO authenticated';
  END IF;
  IF to_regclass('public.pos_registers') IS NULL THEN
    RAISE NOTICE 'pos_registers missing — apply 20260828210000_pos_registers.sql';
  ELSE
    EXECUTE 'GRANT SELECT ON TABLE public.pos_registers TO authenticated';
  END IF;
END $$;

-- ── RLS: org member SELECT; writes only where a policy remains (admin connections) ─
DROP POLICY IF EXISTS "pos_sales_events_org_select" ON public.pos_sales_events;
CREATE POLICY "pos_sales_events_org_select"
  ON public.pos_sales_events
  FOR SELECT
  TO authenticated
  USING (public.is_org_member(org_id));

DO $$
BEGIN
  IF to_regclass('public.pos_audit_events') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP POLICY IF EXISTS "pos_audit_events_org_select" ON public.pos_audit_events';
  EXECUTE $p$
    CREATE POLICY "pos_audit_events_org_select"
      ON public.pos_audit_events
      FOR SELECT
      TO authenticated
      USING (public.is_org_member(org_id))
  $p$;
END $$;

DO $$
BEGIN
  IF to_regclass('public.pos_register_sessions') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP POLICY IF EXISTS "pos_register_sessions_org_select" ON public.pos_register_sessions';
  EXECUTE $p$
    CREATE POLICY "pos_register_sessions_org_select"
      ON public.pos_register_sessions
      FOR SELECT
      TO authenticated
      USING (public.is_org_member(org_id))
  $p$;
  EXECUTE 'DROP POLICY IF EXISTS "pos_register_sessions_org_write" ON public.pos_register_sessions';
  EXECUTE 'DROP POLICY IF EXISTS "pos_register_sessions_org_update" ON public.pos_register_sessions';
END $$;

DO $$
BEGIN
  IF to_regclass('public.pos_registers') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP POLICY IF EXISTS "pos_registers_org_select" ON public.pos_registers';
  EXECUTE $p$
    CREATE POLICY "pos_registers_org_select"
      ON public.pos_registers
      FOR SELECT
      TO authenticated
      USING (public.is_org_member(org_id))
  $p$;
  EXECUTE 'DROP POLICY IF EXISTS "pos_registers_org_manage" ON public.pos_registers';
END $$;

DO $$
BEGIN
  IF to_regclass('public.pos_connections') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP POLICY IF EXISTS "pos_connections_org_select" ON public.pos_connections';
  EXECUTE $p$
    CREATE POLICY "pos_connections_org_select"
      ON public.pos_connections
      FOR SELECT
      TO authenticated
      USING (public.is_org_member(org_id))
  $p$;
  EXECUTE 'DROP POLICY IF EXISTS "pos_connections_org_manage" ON public.pos_connections';
END $$;

-- ── Integrity: brand, staff, register, sale FKs must stay inside the org ───────
CREATE OR REPLACE FUNCTION public.pos_register_org_integrity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.company_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.companies c
    WHERE c.id = NEW.company_id AND c.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS register brand must belong to the organization';
  END IF;

  IF NEW.assigned_staff_id IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM public.memberships m
       WHERE m.org_id = NEW.org_id AND m.user_id = NEW.assigned_staff_id
     )
     AND NOT EXISTS (
       SELECT 1 FROM public.organizations o
       WHERE o.id = NEW.org_id AND o.owner_id = NEW.assigned_staff_id
     )
  THEN
    RAISE EXCEPTION 'POS register staff must belong to the organization';
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.pos_registers') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP TRIGGER IF EXISTS tr_pos_register_org_integrity ON public.pos_registers';
  EXECUTE $t$
    CREATE TRIGGER tr_pos_register_org_integrity
    BEFORE INSERT OR UPDATE ON public.pos_registers
    FOR EACH ROW
    EXECUTE FUNCTION public.pos_register_org_integrity()
  $t$;
END $$;

CREATE OR REPLACE FUNCTION public.pos_session_org_integrity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.pos_registers r
    WHERE r.id = NEW.register_id AND r.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS session register must belong to the organization';
  END IF;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.pos_register_sessions') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP TRIGGER IF EXISTS tr_pos_session_org_integrity ON public.pos_register_sessions';
  EXECUTE $t$
    CREATE TRIGGER tr_pos_session_org_integrity
    BEFORE INSERT OR UPDATE ON public.pos_register_sessions
    FOR EACH ROW
    EXECUTE FUNCTION public.pos_session_org_integrity()
  $t$;
END $$;

CREATE OR REPLACE FUNCTION public.pos_sale_org_integrity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.connection_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_connections c
    WHERE c.id = NEW.connection_id AND c.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS sale connection must belong to the organization';
  END IF;

  IF NEW.register_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_registers r
    WHERE r.id = NEW.register_id AND r.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS sale register must belong to the organization';
  END IF;

  IF NEW.session_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_register_sessions s
    WHERE s.id = NEW.session_id AND s.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS sale session must belong to the organization';
  END IF;

  IF NEW.parent_event_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_sales_events p
    WHERE p.id = NEW.parent_event_id AND p.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS return must reference a sale in the same organization';
  END IF;

  IF NEW.company_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.companies c
    WHERE c.id = NEW.company_id AND c.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS sale brand must belong to the organization';
  END IF;

  IF NEW.client_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.clients cl
    WHERE cl.id = NEW.client_id AND cl.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS sale customer must belong to the organization';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_pos_sale_org_integrity ON public.pos_sales_events;
CREATE TRIGGER tr_pos_sale_org_integrity
BEFORE INSERT OR UPDATE ON public.pos_sales_events
FOR EACH ROW
EXECUTE FUNCTION public.pos_sale_org_integrity();

CREATE OR REPLACE FUNCTION public.pos_audit_org_integrity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.sale_event_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_sales_events s
    WHERE s.id = NEW.sale_event_id AND s.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS audit sale must belong to the organization';
  END IF;

  IF NEW.payment_intent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.payment_intents i
    WHERE i.id = NEW.payment_intent_id AND i.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'POS audit payment intent must belong to the organization';
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.pos_audit_events') IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'DROP TRIGGER IF EXISTS tr_pos_audit_org_integrity ON public.pos_audit_events';
  EXECUTE $t$
    CREATE TRIGGER tr_pos_audit_org_integrity
    BEFORE INSERT OR UPDATE ON public.pos_audit_events
    FOR EACH ROW
    EXECUTE FUNCTION public.pos_audit_org_integrity()
  $t$;
END $$;

CREATE OR REPLACE FUNCTION public.payment_intent_org_integrity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.company_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.companies c
    WHERE c.id = NEW.company_id AND c.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'Payment intent brand must belong to the organization';
  END IF;

  IF NEW.client_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.clients cl
    WHERE cl.id = NEW.client_id AND cl.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'Payment intent customer must belong to the organization';
  END IF;

  IF NEW.pos_sale_event_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.pos_sales_events s
    WHERE s.id = NEW.pos_sale_event_id AND s.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'Payment intent POS sale must belong to the organization';
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.payment_intents') IS NULL THEN
    RAISE NOTICE 'payment_intents missing — apply 20260828180000_payment_intents.sql then re-run this file';
    RETURN;
  END IF;
  EXECUTE 'DROP TRIGGER IF EXISTS tr_payment_intent_org_integrity ON public.payment_intents';
  EXECUTE $t$
    CREATE TRIGGER tr_payment_intent_org_integrity
    BEFORE INSERT OR UPDATE ON public.payment_intents
    FOR EACH ROW
    EXECUTE FUNCTION public.payment_intent_org_integrity()
  $t$;
END $$;

COMMENT ON TABLE public.pos_sales_events IS
  'Normalized POS sale events. Org-scoped. Clients SELECT only; the API writes after server-priced checkout.';

NOTIFY pgrst, 'reload schema';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828270000_organizations_business_type.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Tenant business model: POS is optional. Service orgs stay on invoices/quotes/clients.
-- retail = Paidly + till; mixed = invoices + till. NULL = service (do not force POS).

ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS business_type text;

ALTER TABLE public.organizations
  DROP CONSTRAINT IF EXISTS organizations_business_type_check;

ALTER TABLE public.organizations
  ADD CONSTRAINT organizations_business_type_check
  CHECK (
    business_type IS NULL
    OR business_type IN ('service', 'retail', 'mixed')
  );

COMMENT ON COLUMN public.organizations.business_type IS
  'How the tenant sells: service (documents only), retail (POS), mixed (documents + POS). NULL is treated as service — POS stays off.';

-- Keep the till for orgs that already run POS (registers or sales).
DO $$
BEGIN
  IF to_regclass('public.pos_registers') IS NOT NULL THEN
    EXECUTE $u$
      UPDATE public.organizations o
      SET business_type = 'mixed'
      WHERE o.business_type IS NULL
        AND EXISTS (SELECT 1 FROM public.pos_registers r WHERE r.org_id = o.id)
    $u$;
  END IF;
  IF to_regclass('public.pos_sales_events') IS NOT NULL THEN
    EXECUTE $u$
      UPDATE public.organizations o
      SET business_type = 'mixed'
      WHERE o.business_type IS NULL
        AND EXISTS (SELECT 1 FROM public.pos_sales_events s WHERE s.org_id = o.id)
    $u$;
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828280000_plans_pos_feature.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Canonical SaaS feature key `pos` on Business+ catalog rows.
-- Enforcement is FAMILY_FEATURES + requireFeature('pos') — not a per-user/org allowlist.

DO $$
BEGIN
  IF to_regclass('public.plans') IS NULL THEN
    RAISE NOTICE 'plans missing — skip pos feature catalog row update';
    RETURN;
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'plans'
      AND column_name = 'features'
  ) THEN
    RAISE NOTICE 'plans.features missing — skip pos feature catalog row update';
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'plans'
      AND column_name = 'plan_family'
  ) THEN
    UPDATE public.plans
    SET features = COALESCE(features, '[]'::jsonb) || '["pos"]'::jsonb
    WHERE (
        plan_family IN ('business', 'growth', 'enterprise')
        OR slug IN (
          'sme',
          'corporate',
          'business_monthly',
          'business_annual',
          'growth_monthly',
          'growth_annual',
          'enterprise_custom'
        )
      )
      AND NOT (COALESCE(features, '[]'::jsonb) ? 'pos');
  ELSE
    UPDATE public.plans
    SET features = COALESCE(features, '[]'::jsonb) || '["pos"]'::jsonb
    WHERE slug IN (
        'sme',
        'corporate',
        'business_monthly',
        'business_annual',
        'growth_monthly',
        'growth_annual',
        'enterprise_custom'
      )
      AND NOT (COALESCE(features, '[]'::jsonb) ? 'pos');
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828290000_pos_staff_invite.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- POS-only staff invites: same Auth + memberships, job_function = pos.
-- Shareable till link is /invite?token=…&next=POS. Do not add a second POS login.

CREATE OR REPLACE FUNCTION public.normalize_job_function(raw text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE lower(trim(replace(coalesce(raw, ''), ' ', '_')))
    WHEN 'human_resources' THEN 'hr'
    WHEN 'sales' THEN 'sales'
    WHEN 'hr' THEN 'hr'
    WHEN 'finance' THEN 'finance'
    WHEN 'operations' THEN 'operations'
    WHEN 'support' THEN 'support'
    WHEN 'marketing' THEN 'marketing'
    WHEN 'it' THEN 'it'
    WHEN 'pos' THEN 'pos'
    WHEN 'cashier' THEN 'pos'
    WHEN 'till' THEN 'pos'
    WHEN 'general' THEN 'general'
    ELSE 'general'
  END;
$$;

DO $$
BEGIN
  IF to_regclass('public.company_invites') IS NULL THEN
    RAISE EXCEPTION 'company_invites missing — apply invite lifecycle migrations before POS staff invites';
  END IF;
END $$;

ALTER TABLE public.company_invites
  ADD COLUMN IF NOT EXISTS job_function text NOT NULL DEFAULT 'general';

ALTER TABLE public.company_invites
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'company_admin';

ALTER TABLE public.company_invites
  ADD COLUMN IF NOT EXISTS transfer_org_ownership boolean NOT NULL DEFAULT false;

ALTER TABLE public.memberships
  ADD COLUMN IF NOT EXISTS job_function text NOT NULL DEFAULT 'general';

COMMENT ON COLUMN public.company_invites.job_function IS
  'Copied onto memberships.job_function on accept. pos = till-only staff (RBAC role stays employee).';

COMMENT ON COLUMN public.company_invites.source IS
  'Who issued the invite: company_admin | platform_admin | pos';

CREATE OR REPLACE FUNCTION public.validate_company_invite_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.company_invites%ROWTYPE;
  v_org_name text;
BEGIN
  IF p_token IS NULL OR trim(p_token) = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'missing_token');
  END IF;

  SELECT * INTO v_row
  FROM public.company_invites
  WHERE token = trim(p_token)
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_found');
  END IF;

  IF v_row.status <> 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_pending', 'status', v_row.status);
  END IF;

  IF v_row.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;

  SELECT o.name INTO v_org_name
  FROM public.organizations o
  WHERE o.id = v_row.org_id;

  RETURN jsonb_build_object(
    'ok', true,
    'invite_id', v_row.id,
    'email', v_row.email,
    'role', v_row.role,
    'job_function', public.normalize_job_function(coalesce(v_row.job_function, 'general')),
    'source', coalesce(v_row.source, 'company_admin'),
    'org_id', v_row.org_id,
    'company_name', coalesce(v_org_name, 'your company'),
    'expires_at', v_row.expires_at,
    'transfer_org_ownership', coalesce(v_row.transfer_org_ownership, false)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.validate_company_invite_token(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.validate_company_invite_token(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.accept_company_invite_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_meta jsonb;
  v_invite_id uuid;
  v_org_id uuid;
  v_role text;
  v_membership_role text;
  v_job_function text;
  v_email text;
  v_onboarding_form text;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  v_meta := public.validate_company_invite_token(p_token);
  IF (v_meta->>'ok')::boolean IS NOT TRUE THEN
    RETURN v_meta;
  END IF;

  v_invite_id := (v_meta->>'invite_id')::uuid;
  v_org_id := (v_meta->>'org_id')::uuid;
  v_role := lower(trim(v_meta->>'role'));
  v_job_function := public.normalize_job_function(
    COALESCE(v_meta->>'job_function', 'general')
  );
  IF lower(trim(coalesce(v_meta->>'source', ''))) = 'pos' THEN
    v_job_function := 'pos';
  END IF;

  SELECT lower(trim(email)) INTO v_email FROM auth.users WHERE id = v_user_id;
  IF v_email IS NULL OR v_email <> lower(trim(v_meta->>'email')) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'email_mismatch');
  END IF;

  v_membership_role := CASE
    WHEN v_role IN ('admin', 'owner', 'company_admin') THEN 'admin'
    WHEN v_role = 'manager' THEN 'manager'
    ELSE 'employee'
  END;

  IF v_job_function = 'pos' THEN
    v_membership_role := 'employee';
  END IF;

  v_onboarding_form := CASE
    WHEN v_membership_role IN ('admin', 'owner') THEN 'admin'
    ELSE 'member'
  END;

  IF EXISTS (
    SELECT 1 FROM public.memberships m
    WHERE m.org_id = v_org_id AND m.user_id = v_user_id
  ) THEN
    UPDATE public.memberships
    SET role = v_membership_role,
        job_function = v_job_function
    WHERE org_id = v_org_id AND user_id = v_user_id;
  ELSE
    INSERT INTO public.memberships (org_id, user_id, role, job_function)
    VALUES (v_org_id, v_user_id, v_membership_role, v_job_function);
  END IF;

  IF coalesce((v_meta->>'transfer_org_ownership')::boolean, false) THEN
    UPDATE public.organizations SET owner_id = v_user_id WHERE id = v_org_id;
    UPDATE public.memberships SET role = 'owner', job_function = 'general' WHERE org_id = v_org_id AND user_id = v_user_id;
    v_onboarding_form := 'admin';
    v_membership_role := 'owner';
    v_job_function := 'general';
  END IF;

  PERFORM public.upsert_user_company_role(
    v_user_id, v_org_id, public.normalize_company_role(v_membership_role), v_onboarding_form, NULL
  );
  PERFORM public.sync_saas_user_roles(v_user_id);

  UPDATE public.company_invites
  SET status = 'accepted', accepted_at = now(), accepted_by = v_user_id
  WHERE id = v_invite_id AND status = 'pending';

  RETURN jsonb_build_object(
    'ok', true,
    'org_id', v_org_id,
    'role', v_membership_role,
    'job_function', v_job_function
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_company_invite_token(text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828300000_pos_registers_unique_per_brand.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Register names are unique per organization + brand, not org-wide.
-- Opening Settings used to auto-insert "Main till", so creating "Main Till"
-- for another brand (or the same brand) hit idx_pos_registers_org_name.

DROP INDEX IF EXISTS public.idx_pos_registers_org_name;

-- COALESCE so two brandless tills cannot share a name (NULL ≠ NULL in unique indexes).
CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_registers_org_brand_name
  ON public.pos_registers (
    org_id,
    COALESCE(company_id, '00000000-0000-0000-0000-000000000000'::uuid),
    lower(btrim(name))
  );

COMMENT ON INDEX public.idx_pos_registers_org_brand_name IS
  'One till name per org brand. Different brands may both use Main till.';

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828310000_pos_only_staff_scope.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- POS-only staff scope: not a second login. Same Auth + memberships.job_function = pos.
-- Cashiers cannot read back-office financial rows via RLS. Checkout clients stay readable.
-- Invite URL is /pos/invite/:token. Optional register_id is the till (not a store).

CREATE OR REPLACE FUNCTION public.is_pos_only_staff()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.memberships m
    JOIN public.organizations o ON o.id = m.org_id
    WHERE m.user_id = auth.uid()
      AND lower(trim(m.role)) = 'employee'
      AND public.normalize_job_function(m.job_function) = 'pos'
      AND o.owner_id IS DISTINCT FROM auth.uid()
  );
$$;

COMMENT ON FUNCTION public.is_pos_only_staff() IS
  'True when the signed-in user is an invited till cashier (employee + job_function pos), not the org owner.';

GRANT EXECUTE ON FUNCTION public.is_pos_only_staff() TO authenticated;

CREATE OR REPLACE FUNCTION public.can_read_org_financial_row(
  target_org_id uuid,
  row_user_id uuid DEFAULT NULL,
  row_created_by uuid DEFAULT NULL,
  row_created_by_id uuid DEFAULT NULL
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.memberships m
    WHERE m.org_id = target_org_id
      AND m.user_id = auth.uid()
  )
  AND NOT public.is_pos_only_staff()
  AND (
    public.is_admin()
    OR public.is_company_manager_for_org(target_org_id)
    OR row_user_id = auth.uid()
    OR row_created_by = auth.uid()
    OR row_created_by_id = auth.uid()
  );
$$;

COMMENT ON FUNCTION public.can_read_org_financial_row(uuid, uuid, uuid, uuid) IS
  'Platform admin + company managers see all org rows; employees see only rows they own/created. POS-only staff never read invoice/quote/payslip financials.';

DO $$
BEGIN
  IF to_regclass('public.clients') IS NOT NULL THEN
    DROP POLICY IF EXISTS "pos staff select clients for checkout" ON public.clients;
    CREATE POLICY "pos staff select clients for checkout" ON public.clients
      FOR SELECT
      USING (
        public.is_pos_only_staff()
        AND EXISTS (
          SELECT 1 FROM public.memberships m
          WHERE m.org_id = clients.org_id AND m.user_id = auth.uid()
        )
      );
  END IF;
END $$;

ALTER TABLE public.company_invites
  ADD COLUMN IF NOT EXISTS register_id uuid;

COMMENT ON COLUMN public.company_invites.register_id IS
  'Optional pos_registers.id the cashier should use after accept. Not a store/location table.';

DO $$
BEGIN
  IF to_regclass('public.pos_registers') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'company_invites_register_id_fkey'
     ) THEN
    ALTER TABLE public.company_invites
      ADD CONSTRAINT company_invites_register_id_fkey
      FOREIGN KEY (register_id) REFERENCES public.pos_registers(id) ON DELETE SET NULL;
  END IF;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.validate_company_invite_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.company_invites%ROWTYPE;
  v_org_name text;
BEGIN
  IF p_token IS NULL OR trim(p_token) = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'missing_token');
  END IF;

  SELECT * INTO v_row
  FROM public.company_invites
  WHERE token = trim(p_token)
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_found');
  END IF;

  IF v_row.status <> 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_pending', 'status', v_row.status);
  END IF;

  IF v_row.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;

  SELECT o.name INTO v_org_name
  FROM public.organizations o
  WHERE o.id = v_row.org_id;

  RETURN jsonb_build_object(
    'ok', true,
    'invite_id', v_row.id,
    'email', v_row.email,
    'role', v_row.role,
    'job_function', public.normalize_job_function(coalesce(v_row.job_function, 'general')),
    'source', coalesce(v_row.source, 'company_admin'),
    'org_id', v_row.org_id,
    'company_name', coalesce(v_org_name, 'your company'),
    'expires_at', v_row.expires_at,
    'transfer_org_ownership', coalesce(v_row.transfer_org_ownership, false),
    'register_id', v_row.register_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.validate_company_invite_token(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.validate_company_invite_token(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.accept_company_invite_token(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_meta jsonb;
  v_invite_id uuid;
  v_org_id uuid;
  v_role text;
  v_membership_role text;
  v_job_function text;
  v_email text;
  v_onboarding_form text;
  v_register_id uuid;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_authenticated');
  END IF;

  v_meta := public.validate_company_invite_token(p_token);
  IF (v_meta->>'ok')::boolean IS NOT TRUE THEN
    RETURN v_meta;
  END IF;

  v_invite_id := (v_meta->>'invite_id')::uuid;
  v_org_id := (v_meta->>'org_id')::uuid;
  v_role := lower(trim(v_meta->>'role'));
  v_job_function := public.normalize_job_function(
    COALESCE(v_meta->>'job_function', 'general')
  );
  IF lower(trim(coalesce(v_meta->>'source', ''))) = 'pos' THEN
    v_job_function := 'pos';
  END IF;
  BEGIN
    v_register_id := NULLIF(v_meta->>'register_id', '')::uuid;
  EXCEPTION
    WHEN others THEN
      v_register_id := NULL;
  END;

  SELECT lower(trim(email)) INTO v_email FROM auth.users WHERE id = v_user_id;
  IF v_email IS NULL OR v_email <> lower(trim(v_meta->>'email')) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'email_mismatch');
  END IF;

  v_membership_role := CASE
    WHEN v_role IN ('admin', 'owner', 'company_admin') THEN 'admin'
    WHEN v_role = 'manager' THEN 'manager'
    ELSE 'employee'
  END;

  IF v_job_function = 'pos' THEN
    v_membership_role := 'employee';
  END IF;

  v_onboarding_form := CASE
    WHEN v_membership_role IN ('admin', 'owner') THEN 'admin'
    ELSE 'member'
  END;

  IF EXISTS (
    SELECT 1 FROM public.memberships m
    WHERE m.org_id = v_org_id AND m.user_id = v_user_id
  ) THEN
    UPDATE public.memberships
    SET role = v_membership_role,
        job_function = v_job_function
    WHERE org_id = v_org_id AND user_id = v_user_id;
  ELSE
    INSERT INTO public.memberships (org_id, user_id, role, job_function)
    VALUES (v_org_id, v_user_id, v_membership_role, v_job_function);
  END IF;

  IF coalesce((v_meta->>'transfer_org_ownership')::boolean, false) THEN
    UPDATE public.organizations SET owner_id = v_user_id WHERE id = v_org_id;
    UPDATE public.memberships SET role = 'owner', job_function = 'general' WHERE org_id = v_org_id AND user_id = v_user_id;
    v_onboarding_form := 'admin';
    v_membership_role := 'owner';
    v_job_function := 'general';
  END IF;

  PERFORM public.upsert_user_company_role(
    v_user_id, v_org_id, public.normalize_company_role(v_membership_role), v_onboarding_form, NULL
  );
  PERFORM public.sync_saas_user_roles(v_user_id);

  IF v_job_function = 'pos' AND v_register_id IS NOT NULL AND to_regclass('public.pos_registers') IS NOT NULL THEN
    UPDATE public.pos_registers
    SET assigned_staff_id = v_user_id
    WHERE id = v_register_id
      AND org_id = v_org_id;
  END IF;

  UPDATE public.company_invites
  SET status = 'accepted', accepted_at = now(), accepted_by = v_user_id
  WHERE id = v_invite_id AND status = 'pending';

  RETURN jsonb_build_object(
    'ok', true,
    'org_id', v_org_id,
    'role', v_membership_role,
    'job_function', v_job_function,
    'scope', CASE WHEN v_job_function = 'pos' THEN 'pos' ELSE 'paidly' END
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_company_invite_token(text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- supabase/migrations/20260828320000_pos_customers.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- POS customers: same public.clients SoR, not a second CRM table.
-- POS-only staff may SELECT/INSERT only rows with pos_enabled = true.
-- Owners/admins keep full dashboard access via existing org member policies.
-- Till checkout must not enumerate the general Paidly client list.

ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS pos_enabled boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.clients.pos_enabled IS
  'When true, this client is a POS customer (created on the till or explicitly enabled). POS-only staff may only see these rows.';

DO $$
BEGIN
  IF to_regclass('public.pos_sales_events') IS NOT NULL THEN
    UPDATE public.clients c
    SET pos_enabled = true
    WHERE c.pos_enabled IS NOT TRUE
      AND EXISTS (
        SELECT 1
        FROM public.pos_sales_events e
        WHERE e.client_id = c.id
          AND e.org_id = c.org_id
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_clients_org_pos_enabled
  ON public.clients (org_id, name)
  WHERE pos_enabled = true;

CREATE OR REPLACE FUNCTION public.enforce_pos_customer_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_pos_only_staff() THEN
    NEW.pos_enabled := true;
    NEW.internal_notes := NULL;
    NEW.notes := NULL;
    NEW.tax_id := NULL;
    NEW.fax := NULL;
    NEW.alternate_email := NULL;
    NEW.website := NULL;
    NEW.address := NULL;
    NEW.industry := NULL;
    NEW.contact_person := NULL;
    IF TG_OP = 'INSERT' THEN
      NEW.created_by_id := COALESCE(NEW.created_by_id, auth.uid());
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.enforce_pos_customer_write() IS
  'POS-only cashiers can only write POS customer rows (name/phone/email). CRM fields stay empty.';

DROP TRIGGER IF EXISTS trg_enforce_pos_customer_write ON public.clients;
CREATE TRIGGER trg_enforce_pos_customer_write
  BEFORE INSERT OR UPDATE ON public.clients
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_pos_customer_write();

DROP POLICY IF EXISTS "pos staff select clients for checkout" ON public.clients;
DROP POLICY IF EXISTS "pos staff select pos customers" ON public.clients;
DROP POLICY IF EXISTS "pos staff insert pos customers" ON public.clients;
DROP POLICY IF EXISTS "pos staff update own pos customers" ON public.clients;

CREATE POLICY "pos staff select pos customers"
  ON public.clients
  FOR SELECT
  USING (
    public.is_pos_only_staff()
    AND clients.pos_enabled = true
    AND EXISTS (
      SELECT 1 FROM public.memberships m
      WHERE m.org_id = clients.org_id AND m.user_id = auth.uid()
    )
  );

CREATE POLICY "pos staff insert pos customers"
  ON public.clients
  FOR INSERT
  WITH CHECK (
    public.is_pos_only_staff()
    AND clients.pos_enabled = true
    AND COALESCE(clients.created_by_id, auth.uid()) = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.memberships m
      WHERE m.org_id = clients.org_id AND m.user_id = auth.uid()
    )
  );

CREATE POLICY "pos staff update own pos customers"
  ON public.clients
  FOR UPDATE
  USING (
    public.is_pos_only_staff()
    AND clients.pos_enabled = true
    AND clients.created_by_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.memberships m
      WHERE m.org_id = clients.org_id AND m.user_id = auth.uid()
    )
  )
  WITH CHECK (
    public.is_pos_only_staff()
    AND clients.pos_enabled = true
    AND clients.created_by_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.memberships m
      WHERE m.org_id = clients.org_id AND m.user_id = auth.uid()
    )
  );
