-- DEPRECATED: single source of truth moved to the database schema.
--
-- NEVER paste or execute this file directly on production.
--
-- Storage bucket visibility is maintained by:
--   - `supabase/schema.postgres.sql`
--   - Supabase migrations in `supabase/migrations/`
--
-- Desired state (authoritative):
--   - `paidly` bucket is intentionally PUBLIC (public = true)
--   - `receipts` and `bank-details` buckets are PRIVATE (public = false)
--
-- Developers:
--   - Use public URLs for paidly logos/branding and public documents.
--   - Use signed URLs (createSignedUrl) for receipts and bank files.
--
-- This file previously created buckets with paidly = private; it has been retired.
